# Generated by Django 4.2.14 on 2024-07-16 03:04

from django.db import migrations, models
import importer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_dataimportsession_field_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportsession',
            name='field_filters',
            field=models.JSONField(blank=True, null=True, validators=[importer.validators.validate_field_defaults], verbose_name='Field Filters'),
        ),
    ]
