# Generated by Django 4.2.20 on 2025-04-07 20:53

from django.db import migrations, models
import importer.validators


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_dataimportsession_field_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportsession",
            name="model_type",
            field=models.CharField(
                help_text="Target model type for this import session",
                max_length=100,
                validators=[importer.validators.validate_importer_model_type],
                verbose_name="Model Type",
            ),
        ),
    ]
