# Generated by Django 5.2.15 on 2026-06-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_dataimportcolumnmap_lookup_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportsession',
            name='completed_row_count_history',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Completed Row Count History'),
        ),
        migrations.AddField(
            model_name='dataimportsession',
            name='row_count_history',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Row Count History'),
        ),
    ]
