# Generated by Django 5.2.16 on 2026-08-08 01:36

import django.core.serializers.json
import importer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0007_dataimportsession_completed_row_count_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportrow",
            name="data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Data",
            ),
        ),
        migrations.AlterField(
            model_name="dataimportrow",
            name="errors",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Errors",
            ),
        ),
        migrations.AlterField(
            model_name="dataimportrow",
            name="row_data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Original row data",
            ),
        ),
        migrations.AlterField(
            model_name="dataimportsession",
            name="columns",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Columns",
            ),
        ),
        migrations.AlterField(
            model_name="dataimportsession",
            name="field_defaults",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                validators=[importer.validators.validate_field_defaults],
                verbose_name="Field Defaults",
            ),
        ),
        migrations.AlterField(
            model_name="dataimportsession",
            name="field_filters",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                validators=[importer.validators.validate_field_defaults],
                verbose_name="Field Filters",
            ),
        ),
        migrations.AlterField(
            model_name="dataimportsession",
            name="field_overrides",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                validators=[importer.validators.validate_field_defaults],
                verbose_name="Field Overrides",
            ),
        ),
    ]
