# Generated by Django 4.2.19 on 2025-02-15 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "plugin",
                    models.CharField(
                        blank=True,
                        help_text="Export plugin name",
                        max_length=100,
                        verbose_name="Plugin",
                    ),
                ),
                (
                    "complete",
                    models.BooleanField(
                        help_text="Data export is complete", verbose_name="Complete"
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Export progress percentage",
                        verbose_name="Progress",
                    ),
                ),
                (
                    "output",
                    models.FileField(
                        blank=True,
                        help_text="Generated output file",
                        null=True,
                        upload_to="export/output",
                        verbose_name="Output File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
