# Generated by Django 5.2.14 on 2026-05-21 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="List of day indices (0=Mon, …, 6=Sun)",
                        verbose_name="Days of Week",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
            },
        ),
        migrations.CreateModel(
            name="ClockEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clock_in", models.DateTimeField(verbose_name="Clock In")),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clock Out"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Stand or area identifier",
                        max_length=100,
                        verbose_name="Location",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clock_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clock Entry",
                "verbose_name_plural": "Clock Entries",
                "ordering": ["-clock_in"],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="attendance.shift",
                        verbose_name="Shift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Assignment",
                "verbose_name_plural": "Shift Assignments",
            },
        ),
    ]
