# Generated by Django 2.2 on 2019-04-12 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190412_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemtracking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
