# Generated by Django 2.2.2 on 2019-06-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_purchaseorderlineitem_notes'),
        ('stock', '0005_auto_20190602_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Purchase order for this stock item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='order.PurchaseOrder'),
        ),
    ]
