# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180415_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocation',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
