# Generated by Django 2.2 on 2019-04-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='notes',
            field=models.CharField(blank=True, help_text='Stock Item Notes', max_length=250),
        ),
    ]
