# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20180416_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='URL',
            field=models.URLField(blank=True, max_length=125),
        ),
    ]
