# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build', '0001_initial'),
        ('stock', '0009_auto_20180416_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='build.Build'),
        ),
    ]
