# Generated by Django 2.2 on 2019-05-01 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20190501_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique ID for the StockItem'),
        ),
    ]
