# Generated by Django 2.2 on 2019-05-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20190502_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='uuid',
        ),
    ]
