# Generated by Django 2.2.5 on 2019-09-08 09:16

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20190908_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Where is this stock item located?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_items', to='stock.StockLocation'),
        ),
    ]
