# Generated by Django 2.2 on 2019-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20190508_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='delete_on_deplete',
            field=models.BooleanField(default=True, help_text='Delete this Stock Item when stock is depleted'),
        ),
    ]
