# Generated by Django 2.2.5 on 2019-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20190913_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
