# Generated by Django 2.2 on 2019-05-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_stockitem_delete_on_deplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
