# Generated by Django 2.2.9 on 2020-02-02 10:24

import InvenTree.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20200202_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=100, validators=[InvenTree.validators.validate_tree_name]),
        ),
    ]
