# Generated by Django 2.2.9 on 2020-02-17 11:09

from django.db import migrations


def update_stock_item_tree(apps, schema_editor):
    # Update the StockItem MPTT model

    StockItem = apps.get_model('stock', 'StockItem')
    StockItem.objects.rebuild()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('stock', '0021_auto_20200215_2232'),
    ]

    operations = [
        migrations.RunPython(update_stock_item_tree)
    ]
