# Generated by Django 2.2.12 on 2020-06-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_auto_20200318_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='expiry',
            field=models.DateField(blank=True, help_text='Expiry date for this item', null=True),
        ),
    ]

