# Generated by Django 3.0.5 on 2020-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_stockitemattachment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemattachment',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
