# Generated by Django 3.0.7 on 2020-11-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0053_auto_20201110_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='build_order',
        ),
    ]
