# Generated by Django 3.2 on 2021-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0059_auto_20210404_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemtracking',
            name='notes_trans',
            field=models.CharField(blank=True, help_text='Untranslated tracking entry notes', max_length=512, verbose_name='Untranslated Notes'),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='title_trans',
            field=models.CharField(blank=True, help_text='Untranslated tracking entry title', max_length=250, verbose_name='Untranslated Title'),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='translation_args',
            field=models.JSONField(help_text='All arguments needed for translationf title or notes', null=True, verbose_name='Translation arguments'),
        ),
    ]
