# Generated by Django 3.2 on 2021-05-10 23:11

from django.db import migrations


def update_history(apps, schema_editor):
    """
    Update each existing StockItemTracking object,
    convert the recorded "quantity" to a delta
    """

    StockItem = apps.get_model('stock', 'stockitem')
    StockItemTracking = apps.get_model('stock', 'stockitemtracking')

    update_count = 0

    for item in StockItem.objects.all():

        history = StockItemTracking.objects.filter(item=item).order_by('date')

        if history.count() == 0:
            continue

        quantity = history[0].quantity

        for entry in history:
            
            q = entry.quantity

            if not q == quantity:

                entry.deltas = {
                    'quantity': float(q),
                }

                entry.save()

                update_count += 1

                quantity = q

    print(f"Updated {update_count} StockItemHistory entries")


def reverse_update(apps, schema_editor):
    """
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_auto_20210511_1713'),
    ]

    operations = [
        migrations.RunPython(update_history, reverse_code=reverse_update)
    ]
