# Generated by Django 3.2.5 on 2021-12-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0071_auto_20211205_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='scheduled_for_deletion',
        ),
    ]
