# Generated by Django 3.2.10 on 2021-12-20 13:54

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0072_remove_stockitem_scheduled_for_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='stock.stockitem', verbose_name='Parent Stock Item'),
        ),
    ]
