# Generated by Django 3.2.15 on 2022-08-07 02:38

import InvenTree.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0081_auto_20220801_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external URL', max_length=200, verbose_name='External Link'),
        ),
    ]
