# Generated by Django 3.2.16 on 2023-02-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0092_alter_stockitem_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'verbose_name': 'Stock Location', 'verbose_name_plural': 'Stock Locations'},
        ),
    ]
