# Generated by Django 3.2.18 on 2023-02-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0094_auto_20230218_2217'),
        ('stock', '0095_stocklocation_external'),
    ]

    operations = [
    ]
