# .github/release.yml

changelog:
  exclude:
    labels:
      - translation
      - translations
      - documentation
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking
    - title: Security Patches
      labels:
        - security
    - title: Database Changes
      labels:
        - migration
    - title: New Features
      labels:
        - Semver-Minor
        - feature
        - enhancement
    - title: Experimental Features
      labels:
        - experimental
    - title: Bug Fixes
      labels:
        - Semver-Patch
        - bug
    - title: Devops / Setup Changes
      labels:
        - docker
        - setup
        - demo
        - CI
    - title: Dependencies
      labels:
        - dependency
    - title: Other Changes
      labels:
        - "*"
