# Generated by Django 5.2.17 on 2026-09-09 06:48

import InvenTree.fields
import InvenTree.validators
import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("stock", "0002_auto_20190525_2226"),
        ("stock", "0003_auto_20190525_2303"),
        ("stock", "0004_auto_20190525_2356"),
        ("stock", "0005_auto_20190602_1944"),
        ("stock", "0006_stockitem_purchase_order"),
        ("stock", "0007_auto_20190618_0042"),
        ("stock", "0008_stockitemtracking_url"),
        ("stock", "0009_auto_20190715_2351"),
        ("stock", "0010_stockitem_build"),
        ("stock", "0011_auto_20190908_0404"),
        ("stock", "0012_auto_20190908_0405"),
        ("stock", "0013_auto_20190908_0916"),
        ("stock", "0014_auto_20190908_0918"),
        ("stock", "0015_auto_20190913_1407"),
        ("stock", "0016_auto_20191118_2146"),
        ("stock", "0017_auto_20191118_2311"),
        ("stock", "0018_auto_20200202_0103"),
        ("stock", "0019_auto_20200202_1024"),
        ("stock", "0020_auto_20200206_1213"),
        ("stock", "0021_auto_20200215_2232"),
        ("stock", "0022_auto_20200217_1109"),
        ("stock", "0023_auto_20200318_1027"),
        ("stock", "0024_auto_20200405_2239"),
        ("stock", "0025_auto_20200405_2243"),
        ("stock", "0026_stockitem_uid"),
        ("stock", "0027_stockitem_sales_order"),
        ("stock", "0028_auto_20200421_0724"),
        ("stock", "0029_auto_20200421_2359"),
        ("stock", "0030_auto_20200422_0015"),
    ]

    dependencies = [
        ("build", "0005_auto_20190604_2217"),
        ("order", "0010_purchaseorderlineitem_notes"),
        ("order", "0023_auto_20200420_2309"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="part",
            field=models.ForeignKey(
                help_text="Base part",
                limit_choices_to={
                    "active": True,
                    "is_template": False,
                    "virtual": False,
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="part.part",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "OK"),
                    (50, "Attention needed"),
                    (55, "Damaged"),
                    (60, "Destroyed"),
                    (70, "Lost"),
                    (110, "Shipped"),
                    (85, "Returned"),
                ],
                default=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Purchase order for this stock item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="order.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="name",
            field=models.CharField(
                max_length=100, validators=[InvenTree.validators.validate_tree_name]
            ),
        ),
        migrations.AlterField(
            model_name="stockitemtracking",
            name="notes",
            field=models.CharField(blank=True, help_text="Entry notes", max_length=512),
        ),
        migrations.AlterField(
            model_name="stockitemtracking",
            name="title",
            field=models.CharField(help_text="Tracking entry title", max_length=250),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Build for this stock item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="build_outputs",
                to="build.build",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="location",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Where is this stock item located?",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="stock_items",
                to="stock.stocklocation",
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="stock.stocklocation",
            ),
        ),
        migrations.RenameField(
            model_name="stockitem",
            old_name="URL",
            new_name="link",
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True, help_text="Link to external URL", max_length=2000
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=5,
                default=1,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockitemtracking",
            name="quantity",
            field=models.DecimalField(
                decimal_places=5,
                default=1,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="notes",
            field=models.TextField(blank=True, help_text="Stock Item Notes", null=True),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitem",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitem",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="stock.stockitem",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitem",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitemtracking",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page for further information",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="uid",
            field=models.CharField(
                blank=True, help_text="Unique identifier field", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="sales_order_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="order.salesorderlineitem",
            ),
        ),
    ]
