# Generated by Django 2.2.2 on 2019-06-17 14:42

import InvenTree.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockitem_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[InvenTree.validators.validate_tree_name]),
        ),
    ]
