# Generated by Django 2.2.2 on 2019-07-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockitemtracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemtracking',
            name='notes',
            field=models.CharField(blank=True, help_text='Entry notes', max_length=512),
        ),
        migrations.AlterField(
            model_name='stockitemtracking',
            name='title',
            field=models.CharField(help_text='Tracking entry title', max_length=250),
        ),
    ]
