# Generated by Django 2.2.4 on 2019-09-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build', '0005_auto_20190604_2217'),
        ('stock', '0009_auto_20190715_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='build',
            field=models.ForeignKey(blank=True, help_text='Build for this stock item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_outputs', to='build.Build'),
        ),
    ]
