# Generated by Django 2.2.5 on 2019-09-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stockitem_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
