# Generated by Django 2.2.9 on 2020-02-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20191118_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Stock Item Notes'),
        ),
    ]
