# Generated by Django 2.2.9 on 2020-02-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('stock', '0021_auto_20200215_2232'),
    ]

    operations = []
