# Generated by Django 3.0.5 on 2020-04-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_stockitem_sales_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='sales_order',
            new_name='sales_order_line',
        ),
    ]
