# Generated by Django 4.2.23 on 2025-07-13 12:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stock.models


class Migration(migrations.Migration):

    replaces = [
        ("stock", "0035_auto_20200502_2308"),
        ("stock", "0036_stockitemattachment"),
        ("stock", "0037_stockitemattachment_user"),
        ("stock", "0038_stockitemattachment_upload_date"),
        ("stock", "0039_auto_20200513_0016"),
        ("stock", "0040_stockitemtestresult"),
        ("stock", "0041_stockitemtestresult_notes"),
        ("stock", "0042_auto_20200523_0121"),
    ]

    dependencies = [
        ("stock", "0034_auto_20200426_0602"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "OK"),
                    (50, "Attention needed"),
                    (55, "Damaged"),
                    (60, "Destroyed"),
                    (70, "Lost"),
                    (65, "Rejected"),
                    (85, "Returned"),
                    (110, "Shipped"),
                    (120, "Used for Build"),
                    (130, "Installed in Stock Item"),
                ],
                default=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="StockItemAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        help_text="Select file to attach", upload_to="attachments"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, help_text="File comment", max_length=100
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="stock.stockitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("upload_date", models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockItemTestResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.CharField(
                        help_text="Test name", max_length=100, verbose_name="Test"
                    ),
                ),
                (
                    "result",
                    models.BooleanField(
                        default=False, help_text="Test result", verbose_name="Result"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Test output value",
                        max_length=500,
                        verbose_name="Value",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Test result attachment",
                        null=True,
                        upload_to=stock.models.rename_stock_item_test_result_attachment,
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="stock.stockitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Test notes",
                        max_length=500,
                        verbose_name="Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Item Test Result",
            },
        ),
    ]
