# Generated by Django 3.0.5 on 2020-05-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_auto_20200525_0420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
    ]
