# Generated by Django 3.0.7 on 2021-01-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0055_auto_20201117_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for stock item. Stock will be considered expired after this date', null=True, verbose_name='Expiry Date'),
        ),
    ]
