# Generated by Django 5.2.17 on 2026-09-09 00:59

import InvenTree.fields
import InvenTree.validators
import common.currency
import common.icons
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import generic.states.fields
import generic.states.validators
import mptt.fields
import stock.generators
import stock.models
import stock.status_codes
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('stock', '0059_auto_20210404_2016'), ('stock', '0060_auto_20210511_1713'), ('stock', '0061_auto_20210511_0911'), ('stock', '0062_auto_20210511_2151'), ('stock', '0063_auto_20210511_2343'), ('stock', '0064_auto_20210621_1724'), ('stock', '0065_auto_20210701_0509'), ('stock', '0066_stockitem_scheduled_for_deletion'), ('stock', '0067_alter_stockitem_part'), ('stock', '0068_stockitem_serial_int'), ('stock', '0069_auto_20211109_2347'), ('stock', '0070_auto_20211128_0151'), ('stock', '0071_auto_20211205_1733'), ('stock', '0072_remove_stockitem_scheduled_for_deletion'), ('stock', '0073_alter_stockitem_belongs_to'), ('stock', '0074_alter_stockitem_batch'), ('stock', '0075_auto_20220515_1440'), ('stock', '0076_alter_stockitem_status'), ('stock', '0077_alter_stockitem_notes'), ('stock', '0078_alter_stockitem_supplier_part'), ('stock', '0079_alter_stocklocation_name'), ('stock', '0080_stocklocation_pathstring'), ('stock', '0081_auto_20220801_0044'), ('stock', '0082_alter_stockitem_link'), ('stock', '0083_stocklocation_icon'), ('stock', '0084_auto_20220903_0154'), ('stock', '0085_auto_20220903_0225'), ('stock', '0086_remove_stockitem_uid'), ('stock', '0087_auto_20220912_2341'), ('stock', '0088_remove_stockitem_infinite'), ('stock', '0089_alter_stockitem_purchase_price'), ('stock', '0090_stocklocation_structural'), ('stock', '0091_alter_stockitem_delete_on_deplete'), ('stock', '0092_alter_stockitem_updated'), ('stock', '0093_auto_20230217_2140'), ('stock', '0094_auto_20230220_0025'), ('stock', '0095_stocklocation_external'), ('stock', '0096_auto_20230330_1121'), ('stock', '0097_alter_stockitem_notes'), ('stock', '0098_auto_20230427_2033'), ('stock', '0099_alter_stockitem_status'), ('stock', '0100_auto_20230515_0004'), ('stock', '0100_stockitem_consumed_by'), ('stock', '0101_stockitemtestresult_metadata'), ('stock', '0102_alter_stockitem_status'), ('stock', '0103_stock_location_types'), ('stock', '0104_alter_stockitem_purchase_price_currency'), ('stock', '0105_stockitemtestresult_template'), ('stock', '0106_auto_20240207_0353'), ('stock', '0107_remove_stockitemtestresult_test_and_more'), ('stock', '0108_auto_20240219_0252'), ('stock', '0109_add_additional_test_fields'), ('stock', '0110_alter_stockitemtestresult_finished_datetime_and_more'), ('stock', '0111_delete_stockitemattachment'), ('stock', '0112_alter_stocklocation_custom_icon_and_more'), ('stock', '0113_stockitem_status_custom_key_and_more'), ('stock', '0114_alter_stocklocation_custom_icon'), ('stock', '0115_auto_20250221_1323'), ('stock', '0116_alter_stockitem_link')]

    dependencies = [
        ('company', '0001_initial'),
        ('django_q', '0007_ormq'),
        ('part', '0074_partcategorystar'),
        ('part', '0121_auto_20240207_0344'),
        ('stock', '0058_stockitem_packaging'),
        ('taggit', '0005_auto_20220424_2025'),
        ('users', '0005_owner_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='delete_on_deplete',
            field=models.BooleanField(default=True, help_text='Delete this Stock Item when stock is depleted', verbose_name='Delete on deplete'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Select Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='users.owner', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='stockitemattachment',
            name='attachment',
            field=models.FileField(help_text='Select file to attach', upload_to='attachments', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='stockitemattachment',
            name='comment',
            field=models.CharField(blank=True, help_text='File comment', max_length=100, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='stockitemattachment',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='stockitemattachment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='stockitemtracking',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external page for further information', max_length=2000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='stockitemtracking',
            name='notes',
            field=models.CharField(blank=True, help_text='Entry notes', max_length=512, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stockitemtracking',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='description',
            field=models.CharField(blank=True, help_text='Description (optional)', max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(help_text='Name', max_length=100, validators=[InvenTree.validators.validate_tree_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Select Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_locations', to='users.owner', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='stock.stocklocation', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='deltas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='tracking_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockitemtracking',
            name='title',
            field=models.CharField(blank=True, help_text='Tracking entry title', max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stockitemtracking',
            name='notes',
            field=models.CharField(blank=True, help_text='Entry notes', max_length=512, null=True, verbose_name='Notes'),
        ),
        migrations.RemoveField(
            model_name='stockitemtracking',
            name='link',
        ),
        migrations.RemoveField(
            model_name='stockitemtracking',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockitemtracking',
            name='system',
        ),
        migrations.RemoveField(
            model_name='stockitemtracking',
            name='title',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='scheduled_for_deletion',
            field=models.BooleanField(default=False, help_text='This StockItem will be deleted by the background worker', verbose_name='Scheduled for deletion'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='part',
            field=models.ForeignKey(help_text='Base part', limit_choices_to={'virtual': False}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='part.part', verbose_name='Base Part'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='serial_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockitemattachment',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external URL', max_length=2000, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='stockitemattachment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Select file to attach', null=True, upload_to='attachments', verbose_name='Attachment'),
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='scheduled_for_deletion',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='belongs_to',
            field=models.ForeignKey(blank=True, help_text='Is this item installed in another item?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_parts', to='stock.stockitem', verbose_name='Installed In'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='batch',
            field=models.CharField(blank=True, default=stock.generators.generate_batch_code, help_text='Batch code for this stock item', max_length=100, null=True, verbose_name='Batch Code'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='metadata',
            field=models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='metadata',
            field=models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'OK'), (50, 'Attention needed'), (55, 'Damaged'), (60, 'Destroyed'), (70, 'Lost'), (65, 'Rejected'), (75, 'Quarantined'), (85, 'Returned')], default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='notes',
            field=InvenTree.fields.InvenTreeNotesField(blank=True, help_text='Stock Item Notes', max_length=50000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='supplier_part',
            field=models.ForeignKey(blank=True, help_text='Select a matching supplier part for this stock item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='company.supplierpart', verbose_name='Supplier Part'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(help_text='Name', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='pathstring',
            field=models.CharField(blank=True, help_text='Path', max_length=250, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external URL', max_length=2000, verbose_name='External Link'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon (optional)', max_length=100, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='barcode_data',
            field=models.CharField(blank=True, help_text='Third party barcode data', max_length=500, verbose_name='Barcode Data'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='barcode_hash',
            field=models.CharField(blank=True, help_text='Unique hash of barcode data', max_length=128, verbose_name='Barcode Hash'),
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='uid',
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='barcode_data',
            field=models.CharField(blank=True, help_text='Third party barcode data', max_length=500, verbose_name='Barcode Data'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='barcode_hash',
            field=models.CharField(blank=True, help_text='Unique hash of barcode data', max_length=128, verbose_name='Barcode Hash'),
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='infinite',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='purchase_price',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency=common.currency.currency_code_default, help_text='Single unit purchase price at time of purchase', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Purchase Price'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='structural',
            field=models.BooleanField(default=False, help_text='Stock items may not be directly located into a structural stock locations, but may be located to child locations.', verbose_name='Structural'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='delete_on_deplete',
            field=models.BooleanField(default=stock.models.default_delete_on_deplete, help_text='Delete this Stock Item when stock is depleted', verbose_name='Delete on deplete'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of last update', null=True, verbose_name='Updated'),
        ),
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'verbose_name': 'Stock Location', 'verbose_name_plural': 'Stock Locations'},
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='external',
            field=models.BooleanField(default=False, help_text='This is an external stock location', verbose_name='External'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='notes',
            field=InvenTree.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', max_length=50000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='consumed_by',
            field=models.ForeignKey(blank=True, help_text='Build order which consumed this stock item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumed_stock', to='build.build', verbose_name='Consumed By'),
        ),
        migrations.AddField(
            model_name='stockitemtestresult',
            name='metadata',
            field=models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'OK'), (50, 'Attention needed'), (55, 'Damaged'), (60, 'Destroyed'), (65, 'Rejected'), (70, 'Lost'), (75, 'Quarantined'), (85, 'Returned')], default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='StockLocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata')),
                ('name', models.CharField(help_text='Name', max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Description (optional)', max_length=250, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Default icon for all locations that have no icon set (optional)', max_length=100, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Stock Location type',
                'verbose_name_plural': 'Stock Location types',
            },
        ),
        migrations.RenameField(
            model_name='stocklocation',
            old_name='icon',
            new_name='custom_icon',
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='custom_icon',
            field=models.CharField(blank=True, db_column='icon', help_text='Icon (optional)', max_length=100, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='location_type',
            field=models.ForeignKey(blank=True, help_text='Stock location type of this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_locations', to='stock.stocklocationtype', verbose_name='Location type'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='purchase_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stockitemtestresult',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='part.parttesttemplate'),
        ),
        migrations.RemoveField(
            model_name='stockitemtestresult',
            name='test',
        ),
        migrations.AlterField(
            model_name='stockitemtestresult',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='part.parttesttemplate'),
        ),
        migrations.AddField(
            model_name='stockitemtestresult',
            name='test_station',
            field=models.CharField(blank=True, help_text='The identifier of the test station where the test was performed', max_length=500, verbose_name='Test station'),
        ),
        migrations.AddField(
            model_name='stockitemtestresult',
            name='finished_datetime',
            field=models.DateTimeField(blank=True, help_text='The timestamp of the test finish', null=True, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='stockitemtestresult',
            name='started_datetime',
            field=models.DateTimeField(blank=True, help_text='The timestamp of the test start', null=True, verbose_name='Started'),
        ),
        migrations.DeleteModel(
            name='StockItemAttachment',
        ),
        migrations.AlterField(
            model_name='stocklocationtype',
            name='icon',
            field=models.CharField(blank=True, help_text='Default icon for all locations that have no icon set (optional)', max_length=100, validators=[common.icons.validate_icon], verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='status_custom_key',
            field=generic.states.fields.ExtraInvenTreeCustomStatusModelField(blank=True, default=None, help_text='Additional status information for this item', null=True, validators=[generic.states.validators.CustomStatusCodeValidator(status_class=stock.status_codes.StockStatus)], verbose_name='Custom status key'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=generic.states.fields.InvenTreeCustomStatusModelField(choices=[(10, 'OK'), (50, 'Attention needed'), (55, 'Damaged'), (60, 'Destroyed'), (65, 'Rejected'), (70, 'Lost'), (75, 'Quarantined'), (85, 'Returned')], default=10, validators=[django.core.validators.MinValueValidator(0), generic.states.validators.CustomStatusCodeValidator(status_class=stock.status_codes.StockStatus)]),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='custom_icon',
            field=models.CharField(blank=True, db_column='icon', help_text='Icon (optional)', max_length=100, null=True, validators=[common.icons.validate_icon], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external URL', max_length=2000, verbose_name='External Link'),
        ),
    ]
