# Generated by Django 4.2.23 on 2025-07-13 12:13

import InvenTree.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stock.generators


class Migration(migrations.Migration):

    replaces = [
        ("stock", "0072_remove_stockitem_scheduled_for_deletion"),
        ("stock", "0073_alter_stockitem_belongs_to"),
        ("stock", "0074_alter_stockitem_batch"),
        ("stock", "0075_auto_20220515_1440"),
        ("stock", "0076_alter_stockitem_status"),
        ("stock", "0077_alter_stockitem_notes"),
    ]

    dependencies = [
        ("stock", "0071_auto_20211205_1733"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="scheduled_for_deletion",
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="belongs_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Is this item installed in another item?",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installed_parts",
                to="stock.stockitem",
                verbose_name="Installed In",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="batch",
            field=models.CharField(
                blank=True,
                default=stock.generators.generate_batch_code,
                help_text="Batch code for this stock item",
                max_length=100,
                null=True,
                verbose_name="Batch Code",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocklocation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "OK"),
                    (50, "Attention needed"),
                    (55, "Damaged"),
                    (60, "Destroyed"),
                    (70, "Lost"),
                    (65, "Rejected"),
                    (75, "Quarantined"),
                    (85, "Returned"),
                ],
                default=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Stock Item Notes",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
    ]
