# Generated by Django 3.2.12 on 2022-04-26 10:19

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0073_alter_stockitem_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='batch',
            field=models.CharField(blank=True, default=stock.models.generate_batch_code, help_text='Batch code for this stock item', max_length=100, null=True, verbose_name='Batch Code'),
        ),
    ]
