# Generated by Django 3.2.14 on 2022-07-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_alter_company_image'),
        ('stock', '0077_alter_stockitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='supplier_part',
            field=models.ForeignKey(blank=True, help_text='Select a matching supplier part for this stock item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='company.supplierpart', verbose_name='Supplier Part'),
        ),
    ]
