# Generated by Django 4.2.23 on 2025-07-13 12:14

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("stock", "0082_alter_stockitem_link"),
        ("stock", "0083_stocklocation_icon"),
        ("stock", "0084_auto_20220903_0154"),
    ]

    dependencies = [
        ("stock", "0081_auto_20220801_0044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external URL",
                max_length=2000,
                verbose_name="External Link",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon (optional)",
                max_length=100,
                verbose_name="Icon",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
    ]
