# Generated by Django 3.2.15 on 2022-09-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0085_auto_20220903_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='uid',
        ),
    ]
