# Generated by Django 3.2.16 on 2022-12-24 12:29

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0090_stocklocation_structural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='delete_on_deplete',
            field=models.BooleanField(default=stock.models.default_delete_on_deplete, help_text='Delete this Stock Item when stock is depleted', verbose_name='Delete on deplete'),
        ),
    ]
