# Generated by Django 3.2.19 on 2023-05-14 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('build', '0042_alter_build_notes'),
        ('stock', '0100_auto_20230515_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='consumed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Build order which consumed this stock item',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='consumed_stock',
                to='build.build',
                verbose_name='Consumed By',
            ),
        )
    ]
