# Generated by Django 4.2.23 on 2025-07-13 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    replaces = [
        ("stock", "0101_stockitemtestresult_metadata"),
        ("stock", "0102_alter_stockitem_status"),
        ("stock", "0103_stock_location_types"),
        ("stock", "0104_alter_stockitem_purchase_price_currency"),
    ]

    dependencies = [
        ("stock", "0100_stockitem_consumed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitemtestresult",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "OK"),
                    (50, "Attention needed"),
                    (55, "Damaged"),
                    (60, "Destroyed"),
                    (65, "Rejected"),
                    (70, "Lost"),
                    (75, "Quarantined"),
                    (85, "Returned"),
                ],
                default=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="StockLocationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description (optional)",
                        max_length=250,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Default icon for all locations that have no icon set (optional)",
                        max_length=100,
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Location type",
                "verbose_name_plural": "Stock Location types",
            },
        ),
        migrations.RenameField(
            model_name="stocklocation",
            old_name="icon",
            new_name="custom_icon",
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="custom_icon",
            field=models.CharField(
                blank=True,
                db_column="icon",
                help_text="Icon (optional)",
                max_length=100,
                verbose_name="Icon",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="location_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Stock location type of this location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_locations",
                to="stock.stocklocationtype",
                verbose_name="Location type",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="purchase_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
    ]
