# Generated by Django 4.2.14 on 2024-08-07 22:40

import InvenTree.generic_fields
import django.core.validators
from django.db import migrations
import stock.status_codes


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0112_alter_stocklocation_custom_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="status_custom_key",
            field=InvenTree.generic_fields.InvenTreeCustomStatusExtraModelField(
                blank=True,
                default=None,
                help_text="Additional status information for this item",
                null=True,
                verbose_name="Custom status key",
            ),
        ),
        migrations.AddField(
            model_name="stockitemtracking",
            name="tracking_type_custom_key",
            field=InvenTree.generic_fields.InvenTreeCustomStatusExtraModelField(
                blank=True,
                default=None,
                help_text="Additional status information for this item",
                null=True,
                verbose_name="Custom status key",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=InvenTree.generic_fields.InvenTreeCustomStatusModelField(
                choices=InvenTree.status_codes.StockStatus.items(),
                default=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockitemtracking",
            name="tracking_type",
            field=InvenTree.generic_fields.InvenTreeCustomStatusModelField(
                default=stock.status_codes.StockHistoryCode["LEGACY"]
            ),
        ),
    ]
