# Generated by Django 4.2.19 on 2025-02-21 13:23

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0113_stockitem_status_custom_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='link',
            field=models.TextField()  # Temporary change to force new ALTER COLUMN operation in the next migration
        ),
    ]
