# Generated by Django 5.2.10 on 2026-02-05 12:18

from django.db import migrations


def add_part_links(apps, schema_editor):
    """Add links to the Part model for all existing StockItemTracking entries."""

    StockItemTracking = apps.get_model('stock', 'StockItemTracking')

    history_entries = []

    for tracking in StockItemTracking.objects.all():

        item = tracking.item

        if item is None:
            continue

        part = item.part

        if part is None:
            continue

        tracking.part = part
        history_entries.append(tracking)
    
    if len(history_entries) > 0:
        StockItemTracking.objects.bulk_update(history_entries, ['part'])
        print(f"\nUpdated {len(history_entries)} StockItemTracking entries with part links")


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0117_stockitemtracking_part_alter_stockitemtracking_item"),
    ]

    operations = [
        migrations.RunPython(
            add_part_links,
            reverse_code=migrations.RunPython.noop,
        )
    ]
