# Generated by Django 5.2.9 on 2026-02-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0117_stocklocation_tenant'),
        ('tenant', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocation',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Tenant this stock location belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='tenant.tenant', verbose_name='Tenant'),
        ),
    ]
