# Generated by Django 5.2.12 on 2026-03-21 08:00

import InvenTree.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0118_auto_20260205_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitemtestresult",
            name="date",
            field=models.DateTimeField(
                default=InvenTree.helpers.current_time,
                verbose_name="Date"
            ),
        ),
    ]
