# Generated by Django 5.2.14 on 2026-06-02 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('stock', '0122_alter_stockitem_creation_date')]

    operations = [migrations.RemoveField(model_name='stockitem', name='review_needed')]
