# Generated by Django 5.2.14 on 2026-06-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0123_remove_stockitem_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="review_needed",
        ),
    ]
