# Generated by Django 5.2.15 on 2026-07-11 03:34

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0123_remove_stockitem_review_needed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="lft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="rght",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
