# Generated by Django 5.2.15 on 2026-07-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0124_alter_mptt_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="level",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="children",
                to="stock.stockitem",
                verbose_name="Parent Stock Item",
            ),
        ),
    ]
