# Generated by Django 5.2.16 on 2026-07-27 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("build", "0059_build_tags"),
        ("company", "0080_company_tags"),
        ("order", "0121_add_line_item_discount"),
        ("part", "0152_alter_partpricing_currency"),
        ("stock", "0125_remove_mptt_fields"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("users", "0015_alter_userprofile_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SerialNumberLock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.IntegerField()),
                ("serial", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("serial__isnull", False), models.Q(("serial", ""), _negated=True)
                ),
                fields=("part", "serial"),
                name="stock_item_unique_part_serial",
            ),
        ),
        migrations.AddConstraint(
            model_name="serialnumberlock",
            constraint=models.UniqueConstraint(
                fields=("scope", "serial"), name="unique_serial_lock"
            ),
        ),
    ]
