# Generated by Django 5.2.16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0126_serial_number_concurrency_guard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockitemtestresult",
            options={
                "ordering": (
                    "-finished_datetime",
                    "-started_datetime",
                    "-date",
                    "-pk",
                ),
                "verbose_name": "Stock Item Test Result",
            },
        ),
    ]
