# Generated by Django 5.2.16 on 2026-08-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0127_alter_stockitemtestresult_options"),
        # Ensure any existing purchase_price data has already been migrated
        # into pricing.StockItemCostEntry / StockItemCost before it is dropped
        ("pricing", "0002_migrate_stock_item_costs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="purchase_price_currency",
        ),
    ]
