# Generated by Django 3.0.7 on 2020-10-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('part', 'Part'), ('stock', 'Stock'), ('build', 'Build'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=20)),
                ('view', models.BooleanField(default=True)),
                ('add', models.BooleanField(default=False)),
                ('change', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(help_text='Select Role', on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='users.Role')),
            ],
        ),
    ]
