# Generated by Django 3.0.7 on 2020-10-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201004_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('part', 'Parts'), ('stock', 'Stock'), ('test', 'Testing'), ('build', 'Build Orders'), ('purchase_order', 'Purchase Orders'), ('sales_order', 'Sales Orders')], help_text='Permission set', max_length=50),
        ),
    ]
