# Generated by Django 3.2.21 on 2023-10-04 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_apitoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apitoken',
            unique_together={('user', 'name')},
        ),
    ]
