# Generated by Django 3.2.23 on 2023-11-09 00:39

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231020_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='key',
            field=models.CharField(db_index=True, default=users.models.default_token, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Key'),
        ),
    ]
