# Generated by Django 3.2.21 on 2023-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20231004_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='revoked',
            field=models.BooleanField(default=False, help_text='Token has been revoked', verbose_name='Revoked'),
        ),
    ]
