# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
 - name: Setup django
   before: |
      export INVENTREE_DB_ENGINE='sqlite3'
      export INVENTREE_DB_NAME='/workspace/InvenTree/dev/database.sqlite3'
      export INVENTREE_MEDIA_ROOT='/workspace/InvenTree/inventree-data/media'
      export INVENTREE_STATIC_ROOT='/workspace/InvenTree/dev/static'
      export PIP_USER='no'

      python3 -m venv venv
      source venv/bin/activate
      pip install invoke
      inv install
      git clone git@github.com:inventree/demo-dataset.git /workspace/InvenTree/inventree-data
      mkdir dev
      inv update
      invoke delete-data -f
      invoke import-records -f /workspace/InvenTree/inventree-data/inventree_data.json

      gp sync-done setup_server

 - name: Start server
   init: gp sync-await setup_server
   command: |
      gp sync-await setup_server
      export INVENTREE_DB_ENGINE='sqlite3'
      export INVENTREE_DB_NAME='/workspace/InvenTree/dev/database.sqlite3'
      export INVENTREE_MEDIA_ROOT='/workspace/InvenTree/inventree-data/media'
      export INVENTREE_STATIC_ROOT='/workspace/InvenTree/dev/static'

      source venv/bin/activate
      inv server

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    pullRequests: false
    pullRequestsFromForks: true
    addBadge: true
    addLabel: gitpod-ready
    addCheck: false
