name: inventree
description: Open Source Inventory Management System
homepage: https://inventree.org
notifications: false
buildpack: https://github.com/mjmair/heroku-buildpack-python#v216-mjmair
env:
  - STACK=heroku-20
  - DISABLE_COLLECTSTATIC=1
  - INVENTREE_DB_ENGINE=sqlite3
  - INVENTREE_DB_NAME=database.sqlite3
  - INVENTREE_PLUGINS_ENABLED
  - INVENTREE_MEDIA_ROOT=/opt/inventree/media
  - INVENTREE_STATIC_ROOT=/opt/inventree/static
  - INVENTREE_PLUGIN_FILE=/opt/inventree/plugins.txt
  - INVENTREE_CONFIG_FILE=/opt/inventree/config.yaml
after_install: contrib/packager.io/postinstall.sh
targets:
  ubuntu-20.04:
    dependencies:
      - curl
      - python3
      - python3-venv
      - nginx|apache2
      - postgresql
      - shared-mime-info
    build_dependencies:
      - shared-mime-info
  debian-11:
    dependencies:
      - curl
      - python3
      - python3-venv
      - nginx|apache2
      - postgresql
      - shared-mime-info
    build_dependencies:
      - shared-mime-info
