# Configuration file for Crowdin project integration
# See: https://crowdin.com/project/inventree

"commit_message": "Fix: New translations %original_file_name% from Crowdin"
"append_commit_message": false
"preserve_hierarchy": true

files:
  - source: /src/backend/InvenTree/locale/en/LC_MESSAGES/django.po
    dest: /%original_path%/%original_file_name%
    translation: /src/backend/InvenTree/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /src/frontend/src/locales/en/messages.po
    dest: /%original_path%/%original_file_name%
    translation: /src/frontend/src/locales/%two_letters_code%/%original_file_name%
