# Generated by Django 4.2.12 on 2024-05-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0008_pluginconfig_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginconfig',
            name='key',
            field=models.CharField(db_index=True, help_text='Key of plugin', max_length=255, unique=True, verbose_name='Key'),
        ),
    ]
