# Generated by Django 4.2.22 on 2025-06-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0010_pluginusersetting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationUserSetting",
        ),
    ]
