# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20180416_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
