# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20180417_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='issued_date',
            field=models.DateField(blank=True, help_text='Date the purchase order was issued', null=True),
        ),
    ]
