# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_auto_20180417_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(blank=True, help_text='Company address', max_length=200),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(help_text='Company naem', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, help_text='Company address', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Company naem', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='supplier.Supplier'),
        ),
    ]
