#!/bin/bash
#
# packager.io postinstall script functions
#

function detect_docker() {
  if [ -n "$(grep docker < /proc/1/cgroup)" ]; then
    DOCKER="yes"
  else
    DOCKER="no"
  fi
}

function detect_initcmd () {
  if [ -n "$(which systemctl 2> /dev/null)" ]; then
    INIT_CMD="systemctl"
  elif [ -n "$(which initctl 2> /dev/null)" ]; then
    INIT_CMD="initctl"
  else
    function sysvinit () {
      service $2 $1
    }
    INIT_CMD="sysvinit"
  fi

  if [ "${DOCKER}" == "yes" ]; then
    INIT_CMD="initctl"
  fi
}

function create_initscripts () {
  echo "# Setting up python enviroment"
  cd ${APP_HOME}
  python3 -m venv env
  # Install invoke for later ci tasks
  pip install invoke

  echo "# Setting up nginx"
  rm /etc/nginx/sites-available/default
  cat <<EOF > /etc/nginx/sites-available/inventree
  server {
    listen          80;
    location / {
      proxy_pass      http://localhost:6000;
    }
  }
EOF

  # Restart nginx
  echo "# Restarting nginx"
  ${INIT_CMD} restart nginx

  echo "# (Re)creating init scripts"
  inventree scale web="1" worker="1"

  echo "# Enabling InvenTree on boot"
  ${INIT_CMD} enable inventree
}

function start_inventree () {
  echo "# Starting InvenTree"
  ${INIT_CMD} start inventree
}

function stop_inventree () {
  echo "# Stopping InvenTree"
  ${INIT_CMD} stop inventree
}

function update_or_install () {
    echo "# Updating InvenTree"
    cd ${APP_HOME} && invoke update
    echo "# Set permissions for data dir and media: ${DATA_DIR}"
    chown ${APP_USER}:${APP_GROUP} ${DATA_DIR} -R
}

function set_env () {
  echo "# Setting up InvenTree config values"

  inventree config:set INVENTREE_MEDIA_ROOT=${INVENTREE_MEDIA_ROOT}
  inventree config:set INVENTREE_STATIC_ROOT=${INVENTREE_STATIC_ROOT}
  inventree config:set INVENTREE_PLUGIN_FILE=${INVENTREE_PLUGIN_FILE}
  inventree config:set INVENTREE_CONFIG_FILE=${INVENTREE_CONFIG_FILE}
  inventree config:set INVENTREE_SECRET_KEY_FILE=${INVENTREE_SECRET_KEY_FILE}
  inventree config:set INVENTREE_DB_NAME=${INVENTREE_DB_NAME}
  inventree config:set INVENTREE_DB_ENGINE=${INVENTREE_DB_ENGINE}
  inventree config:set INVENTREE_PLUGINS_ENABLED=${INVENTREE_PLUGINS_ENABLED}
}


function final_message () {
  echo -e "####################################################################################"
  echo -e "\nAdd your fully qualified domain name or public IP to servername directive of"
  echo -e "nginx, if this installation is done on a remote server. You have to change:"
  echo -e "/etc/nginx/sites-available/inventree and restart nginx process."
  echo -e "Otherwise just open http://localhost/ in your browser to start using InvenTree.\n"
  echo -e "####################################################################################"
}
