# Generated by Django 5.2.15 on 2026-09-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcard', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcard',
            name='karat',
            field=models.CharField(blank=True, help_text='Karat value of the metal, e.g. 14KT, 18KT.', max_length=20, null=True, verbose_name='Kt'),
        ),
    ]
