# Generated by Django 4.2.17 on 2025-06-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('company', '0002_auto_20190520_2204'), ('company', '0003_remove_supplierpart_minimum'), ('company', '0004_auto_20190525_2354'), ('company', '0005_auto_20190525_2356')]

    dependencies = [
        ('company', '0001_initial'),
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpart',
            name='part',
            field=models.ForeignKey(help_text='Select part', limit_choices_to={'purchaseable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_parts', to='part.part'),
        ),
        migrations.AddField(
            model_name='supplierpart',
            name='supplier',
            field=models.ForeignKey(help_text='Select supplier', limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='company.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.company'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierpricebreak',
            unique_together={('part', 'quantity')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierpart',
            unique_together={('part', 'supplier', 'SKU')},
        ),
        migrations.RemoveField(
            model_name='supplierpart',
            name='minimum',
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='part',
            field=models.ForeignKey(help_text='Select part', limit_choices_to={'has_variants': False, 'purchaseable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_parts', to='part.part'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='part',
            field=models.ForeignKey(help_text='Select part', limit_choices_to={'is_template': False, 'purchaseable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_parts', to='part.part'),
        ),
    ]
