# Generated by Django 2.2 on 2019-05-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190520_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpart',
            name='minimum',
        ),
    ]
