# Generated by Django 2.2.9 on 2020-03-18 11:14

import InvenTree.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20200201_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='cost',
            field=InvenTree.fields.RoundingDecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
