# Generated by Django 2.2.10 on 2020-04-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200318_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='URL',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='supplierpart',
            old_name='URL',
            new_name='link',
        ),
    ]
