# Generated by Django 2.2.10 on 2020-04-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20200413_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpart',
            name='manufacturer_name',
        ),
    ]
