# Generated by Django 3.0.7 on 2020-11-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_remove_supplierpricebreak_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpricebreak',
            name='cost',
        ),
    ]
