# Generated by Django 3.0.7 on 2021-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20210403_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the company', max_length=500, verbose_name='Company description'),
        ),
    ]
