# Generated by Django 4.2.23 on 2025-07-13 11:25

import InvenTree.fields
import InvenTree.validators
import common.currency
import company.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import stdimage.models
import taggit.managers


class Migration(migrations.Migration):

    replaces = [
        ("company", "0037_supplierpart_update_3"),
        ("company", "0038_manufacturerpartparameter"),
        ("company", "0039_auto_20210701_0509"),
        ("company", "0040_alter_company_currency"),
        ("company", "0041_alter_company_options"),
        ("company", "0042_supplierpricebreak_updated"),
        ("company", "0043_manufacturerpartattachment"),
        ("company", "0044_auto_20220607_2204"),
        ("company", "0045_alter_company_notes"),
        ("company", "0046_alter_company_image"),
        ("company", "0047_supplierpart_pack_size"),
        ("company", "0048_auto_20220913_0312"),
        ("company", "0049_company_metadata"),
        ("company", "0050_alter_company_website"),
        ("company", "0051_alter_supplierpricebreak_price"),
        ("company", "0052_alter_supplierpricebreak_updated"),
        ("company", "0053_supplierpart_updated"),
        ("company", "0054_companyattachment"),
        ("company", "0055_auto_20230317_0816"),
        ("company", "0056_alter_company_notes"),
        ("company", "0057_auto_20230427_2033"),
        ("company", "0058_auto_20230515_0004"),
    ]

    dependencies = [
        ("company", "0036_supplierpart_update_2"),
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0004_inventreesetting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierpart",
            name="MPN",
        ),
        migrations.RemoveField(
            model_name="supplierpart",
            name="manufacturer",
        ),
        migrations.CreateModel(
            name="ManufacturerPartParameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Parameter name", max_length=500, verbose_name="Name"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Parameter value",
                        max_length=500,
                        verbose_name="Value",
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        blank=True,
                        help_text="Parameter units",
                        max_length=64,
                        null=True,
                        verbose_name="Units",
                    ),
                ),
                (
                    "manufacturer_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="company.manufacturerpart",
                        verbose_name="Manufacturer Part",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturer Part Parameter",
                "unique_together": {("manufacturer_part", "name")},
            },
        ),
        migrations.AlterField(
            model_name="supplierpricebreak",
            name="price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                currency_choices=[],
                decimal_places=4,
                default_currency="",
                help_text="Unit price at specified quantity",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="supplierpricebreak",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="currency",
            field=models.CharField(
                blank=True,
                default=common.currency.currency_code_default,
                help_text="Default currency used for this company",
                max_length=3,
                validators=[InvenTree.validators.validate_currency_code],
                verbose_name="Currency",
            ),
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="ManufacturerPartAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Select file to attach",
                        null=True,
                        upload_to="attachments",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "link",
                    InvenTree.fields.InvenTreeURLField(
                        blank=True,
                        help_text="Link to external URL",
                        max_length=2000,
                        null=True,
                        verbose_name="Link",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="File comment",
                        max_length=100,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "upload_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="upload date"
                    ),
                ),
                (
                    "manufacturer_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="company.manufacturerpart",
                        verbose_name="Manufacturer Part",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="availability_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of last update of availability data",
                null=True,
                verbose_name="Availability Updated",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="available",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Quantity available from supplier",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Available",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Company Notes",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to=company.models.rename_company_image,
                variations={"preview": (256, 256), "thumbnail": (128, 128)},
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="pack_size",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=5,
                default=1,
                help_text="Unit quantity supplied in a single pack",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.001)],
                verbose_name="Pack Quantity",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Company website URL",
                max_length=2000,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="supplierpricebreak",
            name="price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Unit price at specified quantity",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Price",
            ),
        ),
        migrations.AddField(
            model_name="supplierpricebreak",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last update",
                null=True,
                verbose_name="Updated",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last update",
                null=True,
                verbose_name="Updated",
            ),
        ),
        migrations.CreateModel(
            name="CompanyAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Select file to attach",
                        null=True,
                        upload_to="attachments",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "link",
                    InvenTree.fields.InvenTreeURLField(
                        blank=True,
                        help_text="Link to external URL",
                        max_length=2000,
                        null=True,
                        verbose_name="Link",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="File comment",
                        max_length=100,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "upload_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="upload date"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="company.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
