# Generated by Django 3.2.5 on 2021-10-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_alter_company_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
    ]
