# Generated by Django 3.2.18 on 2023-04-19 00:37

from django.db import migrations

import InvenTree.fields


class Migration(migrations.Migration):
    dependencies = [('company', '0055_auto_20230317_0816')]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text='Markdown notes (optional)',
                max_length=50000,
                null=True,
                verbose_name='Notes',
            ),
        )
    ]
