# Generated by Django 3.2.19 on 2023-05-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_auto_20230519_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpart',
            name='pack_size',
        ),
    ]
