# Generated by Django 4.2.23 on 2025-07-13 11:25

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    replaces = [
        ("company", "0065_remove_company_address"),
        ("company", "0066_auto_20230616_2059"),
        ("company", "0067_alter_supplierpricebreak_price_currency"),
        ("company", "0068_auto_20231120_1108"),
        ("company", "0069_company_active"),
    ]

    dependencies = [
        ("company", "0064_move_address_field_to_address_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="address",
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_city",
            field=models.CharField(
                blank=True,
                help_text="Postal code city/region",
                max_length=50,
                verbose_name="City/Region",
            ),
        ),
        migrations.AlterField(
            model_name="supplierpricebreak",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is this company active?", verbose_name="Active"
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Is this supplier part active?",
                verbose_name="Active",
            ),
        ),
    ]
