# Generated by Django 3.2.19 on 2023-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_remove_company_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_city',
            field=models.CharField(blank=True, help_text='Postal code city/region', max_length=50, verbose_name='City/Region'),
        ),
    ]
