# Generated by Django 4.2.11 on 2024-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0068_auto_20231120_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this company active?', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='supplierpart',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this supplier part active?', verbose_name='Active'),
        ),
    ]
