# Generated by Django 4.2.12 on 2024-06-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_company_active'),
        ('common', '0026_auto_20240608_1238')
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAttachment',
        ),
        migrations.DeleteModel(
            name='ManufacturerPartAttachment',
        ),
    ]
