# Generated by Django 4.2.11 on 2024-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_company_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpart',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this supplier part active?', verbose_name='Active'),
        ),
    ]
