# Generated by Django 4.2.23 on 2025-07-13 11:25

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("company", "0071_manufacturerpart_notes_supplierpart_notes"),
        ("company", "0072_auto_20250221_1236"),
        ("company", "0073_alter_address_link_alter_company_link_and_more"),
        ("company", "0074_alter_manufacturerpart_link"),
    ]

    dependencies = [
        (
            "company",
            "0070_remove_manufacturerpartattachment_manufacturer_part_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturerpart",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierpart",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturerpart",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to address information (external)",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external company information",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Company website URL",
                max_length=2000,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="supplierpart",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="URL for external supplier part link",
                max_length=2000,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturerpart",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="URL for external manufacturer part link",
                max_length=2000,
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
