# Generated by Django 4.2.19 on 2025-02-21 14:51

import InvenTree.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0073_alter_address_link_alter_company_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturerpart",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="URL for external manufacturer part link",
                max_length=2000,
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
