# Generated by Django 4.2.22 on 2025-07-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0074_alter_manufacturerpart_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
    ]
