# Generated by Django 4.2.22 on 2025-07-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_company_tax_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
    ]
