# Generated by Django 5.2.8 on 2025-11-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0076_alter_company_image"),
        ("common", "0041_auto_20251028_1112"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManufacturerPartParameter",
        ),
    ]
