# Generated by Django 5.2.9 on 2026-01-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0077_delete_manufacturerpartparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(blank=True, help_text='Address line 1', max_length=200, verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, help_text='Address line 2', max_length=200, verbose_name='Line 2'),
        ),
    ]
