# Generated by Django 5.2.11 on 2026-02-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0077_delete_manufacturerpartparameter"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpart",
            name="primary",
            field=models.BooleanField(
                default=False,
                help_text="Is this the primary supplier part for the linked Part?",
                verbose_name="Primary",
            ),
        ),
    ]
