# Generated by Django 4.2.22 on 2025-08-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0077_delete_manufacturerpartparameter'),
        ('common', '0044_migrate_company_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
    ]
