# Generated by Django 5.2.14 on 2026-05-31 03:39

import django.db.models.deletion
from django.db import migrations, models


def remove_orphaned_addresses(apps, schema_editor):
    """Remove any Address objects which are not linked to a Company."""

    Address = apps.get_model("company", "Address")

    orphaned_addresses = Address.objects.filter(company=None)

    if len(orphaned_addresses) > 0:
        print(f"Removing {len(orphaned_addresses)} orphaned Address objects")
        orphaned_addresses.delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("company", "0079_auto_20260212_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Select company",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="company.company",
                verbose_name="Company",
            ),
        ),
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=remove_orphaned_addresses,
        )
    ]
