# Generated by Django 5.2.14 on 2026-05-31 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0079_auto_20260212_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Select company",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="company.company",
                verbose_name="Company",
            ),
        ),
    ]
