# Generated by Django 5.2.14 on 2026-06-03 10:07

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0079_auto_20260212_1054"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
