# Generated by Django 5.2.14 on 2026-05-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0080_company_tags"),
        ("common", "0048_remove_notesimage_model_id_and_more")
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="manufacturerpart",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="supplierpart",
            name="notes",
        ),
    ]
