# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 05:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParameterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Category Parameter',
                'verbose_name_plural': 'Category Parameters',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('IPN', models.CharField(blank=True, max_length=100)),
                ('minimum_stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('units', models.CharField(blank=True, default='pcs', max_length=20)),
                ('trackable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='part.PartCategory')),
            ],
            options={
                'verbose_name': 'Part Category',
                'verbose_name_plural': 'Part Categories',
            },
        ),
        migrations.CreateModel(
            name='PartParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50)),
                ('min_value', models.CharField(blank=True, max_length=50)),
                ('max_value', models.CharField(blank=True, max_length=50)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='part.Part')),
            ],
            options={
                'verbose_name': 'Part Parameter',
                'verbose_name_plural': 'Part Parameters',
            },
        ),
        migrations.CreateModel(
            name='PartParameterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('units', models.CharField(blank=True, max_length=10)),
                ('format', models.PositiveIntegerField(choices=[(10, 'Numeric'), (20, 'Text'), (30, 'Bool')], default=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Parameter Template',
                'verbose_name_plural': 'Parameter Templates',
            },
        ),
        migrations.AddField(
            model_name='partparameter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.PartParameterTemplate'),
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.PartCategory'),
        ),
        migrations.AddField(
            model_name='categoryparameterlink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.PartCategory'),
        ),
        migrations.AddField(
            model_name='categoryparameterlink',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.PartParameterTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='partparameter',
            unique_together=set([('part', 'template')]),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set([('name', 'category'), ('IPN', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='categoryparameterlink',
            unique_together=set([('category', 'template')]),
        ),
    ]
