# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryparameterlink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='categoryparameterlink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryparameterlink',
            name='template',
        ),
        migrations.AlterUniqueTogether(
            name='partparameter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='part',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='template',
        ),
        migrations.DeleteModel(
            name='CategoryParameterLink',
        ),
        migrations.DeleteModel(
            name='PartParameter',
        ),
        migrations.DeleteModel(
            name='PartParameterTemplate',
        ),
    ]
