# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_auto_20180412_0600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set([('name', 'category')]),
        ),
    ]
