# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_auto_20180412_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='part.PartCategory'),
        ),
    ]
