# Generated by Django 2.2 on 2019-05-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_auto_20190525_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='has_variants',
            new_name='is_template',
        ),
        migrations.AlterField(
            model_name='part',
            name='variant_of',
            field=models.ForeignKey(blank=True, help_text='Is this part a variant of another part?', limit_choices_to={'active': True, 'is_template': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='part.Part'),
        ),
    ]
