# Generated by Django 2.2 on 2019-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_auto_20190412_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='note',
            field=models.CharField(blank=True, help_text='Item notes', max_length=100),
        ),
    ]
