# Generated by Django 2.2 on 2019-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0004_bomitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='consumable',
            field=models.BooleanField(default=False, help_text='Can this part be used to build other parts?'),
        ),
    ]
