# Generated by Django 2.2 on 2019-04-16 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0005_part_consumable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='sub_part',
            field=models.ForeignKey(limit_choices_to={'consumable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='part.Part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='consumable',
            field=models.BooleanField(default=True, help_text='Can this part be used to build other parts?'),
        ),
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
