# Generated by Django 2.2 on 2019-04-16 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0006_auto_20190416_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpart',
            name='note',
            field=models.CharField(blank=True, help_text='Notes', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='base_cost',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Minimum charge (e.g. stocking fee)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='description',
            field=models.CharField(blank=True, help_text='Supplier part description', max_length=250),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='minimum',
            field=models.PositiveIntegerField(default=1, help_text='Minimum order quantity (MOQ)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='multiple',
            field=models.PositiveIntegerField(default=1, help_text='Order multiple', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='packaging',
            field=models.CharField(blank=True, help_text='Part packaging', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='single_price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Price for single quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
