# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 04:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0006_auto_20180414_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='part.Part')),
                ('sub_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='part.Part')),
            ],
            options={
                'verbose_name': 'BOM Item',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together=set([('part', 'sub_part')]),
        ),
    ]
