# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0008_part_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, upload_to='part_images'),
        ),
    ]
