# Generated by Django 2.2 on 2019-04-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0010_auto_20190417_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpart',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='company.Company'),
        ),
    ]
