# Generated by Django 2.2 on 2019-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0011_auto_20190428_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='partattachment',
            name='comment',
            field=models.CharField(blank=True, help_text='File comment', max_length=100),
        ),
    ]
