# Generated by Django 2.2 on 2019-04-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0013_auto_20190429_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='partattachment',
            name='comment',
            field=models.CharField(blank=True, help_text='Attachment description', max_length=100),
        ),
    ]
