# Generated by Django 2.2 on 2019-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0013_auto_20190429_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='URL',
            field=models.URLField(blank=True, help_text='Link to extenal URL'),
        ),
    ]
