# Generated by Django 2.2 on 2019-05-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_stockitem_uuid'),
        ('part', '0014_auto_20190502_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='default_location',
            field=models.ForeignKey(blank=True, help_text='Default location for parts in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='stock.StockLocation'),
        ),
    ]
