# Generated by Django 2.2 on 2019-05-04 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('part', '0016_partstar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partstar',
            unique_together={('part', 'user')},
        ),
    ]
