# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0016_auto_20180415_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='purchaseable',
            field=models.BooleanField(default=True),
        ),
    ]
