# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0017_part_purchaseable'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='buildable',
            field=models.BooleanField(default=False),
        ),
    ]
