# Generated by Django 2.2.4 on 2019-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0017_bomitem_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partparametertemplate',
            name='name',
            field=models.CharField(help_text='Parameter Name', max_length=100, unique=True),
        ),
    ]
