# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0018_part_buildable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='IPN',
            field=models.CharField(blank=True, help_text='Internal Part Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='URL',
            field=models.URLField(blank=True, help_text='Link to extenal URL'),
        ),
        migrations.AlterField(
            model_name='part',
            name='buildable',
            field=models.BooleanField(default=False, help_text='Can this part be built from other parts?'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Part category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parts', to='part.PartCategory'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(help_text='Part description', max_length=250),
        ),
        migrations.AlterField(
            model_name='part',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0, help_text='Minimum allowed stock level', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(help_text='Part name (must be unique)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='purchaseable',
            field=models.BooleanField(default=True, help_text='Can this part be purchased from external suppliers?'),
        ),
        migrations.AlterField(
            model_name='part',
            name='trackable',
            field=models.BooleanField(default=False, help_text='Does this part have tracking for unique items?'),
        ),
    ]
