# Generated by Django 2.2 on 2019-05-08 13:32

from django.db import migrations, models
import django.db.models.deletion
import part.models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0018_auto_20190505_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='units',
            field=models.CharField(blank=True, default='pcs', help_text='Stock keeping units for this part', max_length=20),
        ),
        migrations.AlterField(
            model_name='partattachment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Select file to attach', null=True, upload_to=part.models.attach_file),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='part',
            field=models.ForeignKey(help_text='Select part', limit_choices_to={'purchaseable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_parts', to='part.Part'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='supplier',
            field=models.ForeignKey(help_text='Select supplier', limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='company.Company'),
        ),
    ]
