# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0019_auto_20180416_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='salable',
            field=models.BooleanField(default=False, help_text='Can this part be sold to customers?'),
        ),
    ]
