# Generated by Django 2.2.5 on 2019-09-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('part', '0019_auto_20190908_0404'),
    ]

    operations = []
