# Generated by Django 2.2 on 2019-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0019_auto_20190508_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='variant',
            field=models.CharField(blank=True, help_text='Part variant or revision code', max_length=32),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(help_text='Part name', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'variant')},
        ),
    ]
