# Generated by Django 2.2.5 on 2019-09-08 04:04

from django.db import migrations

def update_tree(apps, schema_editor):
    # Update the PartCategory MPTT model

    try:
        print("Rebuilding PartCategory objects")

        from part.models import PartCategory
        PartCategory.objects.rebuild()
    except Exception:
        print("Error rebuilding PartCategory objects")

    try:
        print("Rebuilding PartCategoryS objects - app loaded")

        PartCategoryS = apps.get_model('part', 'PartCategory')
        PartCategoryS.objects.rebuild()
    except Exception:
        print("Error rebuilding PartCategory objects - app loaded")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('part', '0019_auto_20190908_0404'),
    ]

    operations = [
        migrations.RunPython(update_tree)
    ]
