# Generated by Django 2.2 on 2019-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0022_auto_20190512_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='keywords',
            field=models.CharField(blank=True, help_text='Part keywords to improve visibility in search results', max_length=250),
        ),
    ]
