# Generated by Django 2.2 on 2019-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0023_part_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='default_keywords',
            field=models.CharField(blank=True, help_text='Default keywords for parts in this category', max_length=250),
        ),
    ]
