# Generated by Django 2.2 on 2019-05-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0025_auto_20190515_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpart',
            name='single_price',
        ),
    ]
