# Generated by Django 2.2 on 2019-05-18 06:27

from django.db import migrations, models
import part.models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0027_auto_20190518_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partattachment',
            name='attachment',
            field=models.FileField(help_text='Select file to attach', upload_to=part.models.attach_file),
        ),
    ]
