# Generated by Django 2.2 on 2019-05-18 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0028_auto_20190518_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
