# Generated by Django 2.2 on 2019-05-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20190518_1759'),
        ('part', '0031_auto_20190518_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierpricebreak',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplierpricebreak',
            name='part',
        ),
        migrations.AlterField(
            model_name='part',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='Default supplier part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_parts', to='company.SupplierPart'),
        ),
        migrations.DeleteModel(
            name='SupplierPart',
        ),
        migrations.DeleteModel(
            name='SupplierPriceBreak',
        ),
    ]
