# Generated by Django 3.0.7 on 2020-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0050_auto_20200917_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='optional',
            field=models.BooleanField(default=False, help_text='This BOM item is optional'),
        ),
    ]
