# Generated by Django 3.0.7 on 2020-10-27 04:57

import InvenTree.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0051_bomitem_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external URL', null=True),
        ),
    ]
