# Generated by Django 3.0.7 on 2020-10-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0051_bomitem_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_parts_1', to='part.Part')),
                ('part_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_parts_2', to='part.Part')),
            ],
        ),
    ]
