# Generated by Django 3.0.7 on 2020-11-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0056_auto_20201110_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsellpricebreak',
            name='currency',
        ),
    ]
