# Generated by Django 3.2.4 on 2021-06-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0067_partinternalpricebreak'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('name', 'IPN', 'revision'), name='unique_part'),
        ),
    ]
