# Generated by Django 3.2.4 on 2021-07-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0069_auto_20210627_1251'),
        ('part', '0070_alter_part_variant_of'),
    ]

    operations = [
    ]
