# Generated by Django 3.2.4 on 2021-10-24 18:36

import InvenTree.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0073_auto_20211013_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPriceCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', InvenTree.fields.RoundingDecimalField(decimal_places=5, max_digits=15, verbose_name='Quantity')),
                ('price_break', models.CharField(max_length=255, verbose_name='Price Break')),
                ('currency_code', models.CharField(max_length=255, verbose_name='Currency')),
                ('price', models.DecimalField(decimal_places=4, help_text='Unit price at specified quantity', max_digits=19, null=True, verbose_name='Price')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_prices', to='part.part', verbose_name='Part')),
            ],
            options={
                'abstract': False,
                'unique_together': {('part', 'quantity', 'price_break', 'currency_code')},
            },
        ),
    ]
