# Generated by Django 3.2.5 on 2021-11-26 00:06

import InvenTree.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0074_partcategorystar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_avg',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=4, default_currency='', help_text='Average purchase price as cache', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Purchase Price Avg'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_avg_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=4, default_currency='', help_text='Maximum purchase price as cache', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Purchase Price Max'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_max_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=4, default_currency='', help_text='Minimum purchase price as cache', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Purchase Price Min'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_min_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
        migrations.CreateModel(
            name='PartPriceCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', InvenTree.fields.RoundingDecimalField(decimal_places=5, max_digits=15, verbose_name='Quantity')),
                ('price_break', models.CharField(max_length=255, verbose_name='Price Break')),
                ('currency_code', models.CharField(max_length=255, verbose_name='Currency')),
                ('price', models.DecimalField(decimal_places=4, help_text='Unit price at specified quantity', max_digits=19, null=True, verbose_name='Price')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_prices', to='part.part', verbose_name='Part')),
            ],
            options={
                'abstract': False,
                'unique_together': {('part', 'quantity', 'price_break', 'currency_code')},
            },
        ),
    ]
