# Generated by Django 3.2.4 on 2021-10-24 20:46

import InvenTree.fields
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0074_partpricecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=4, default_currency='', help_text='Minimum purchase price as cache', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Purchase Price Min'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='purchase_price_min_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
    ]
