# Generated by Django 3.2.13 on 2022-05-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0076_auto_20220516_0819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together=set(),
        ),
    ]
