# Generated by Django 3.2.13 on 2022-06-16 11:56

from django.db import migrations


def regenerate_thumbnails(apps, schema_editor):
    """Regenerate thumbnails for all part images.

    - PR https://github.com/inventree/InvenTree/pull/3185 introduces a new level of thumbnail image
    """

    from part.models import Part

    for prt in Part.objects.all():
        if prt.image:
            prt.image.render_variations(replace=False)


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0078_auto_20220606_0024'),
    ]

    operations = [
        migrations.RunPython(
            regenerate_thumbnails,
            reverse_code=regenerate_thumbnails,
        )
    ]
