# Generated by Django 3.2.14 on 2022-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0080_alter_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partinternalpricebreak',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='partsellpricebreak',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
