# Generated by Django 3.2.14 on 2022-07-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0081_alter_partcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='pathstring',
            field=models.CharField(blank=True, help_text='Path', max_length=250, verbose_name='Path'),
        ),
    ]
