# Generated by Django 3.2.16 on 2022-11-11 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0090_auto_20221111_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='base_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Minimum charge (e.g. stocking fee)', max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base cost'),
        ),
    ]
