# Generated by Django 3.2.16 on 2023-02-02 00:32

import InvenTree.fields
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0094_alter_part_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='partpricing',
            name='stock_item_cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Minimum cost of individual stock items for this part', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Stock Price'),
        ),
        migrations.AddField(
            model_name='partpricing',
            name='stock_item_cost_max_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='partpricing',
            name='stock_item_cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Minimum cost of individual stock items for this part', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Stock Price'),
        ),
        migrations.AddField(
            model_name='partpricing',
            name='stock_item_cost_min_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
    ]
