# Generated by Django 3.2.16 on 2023-02-18 22:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('part', '0098_auto_20230214_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
