# Generated by Django 3.2.16 on 2023-02-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0098_auto_20230214_1115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partcategory',
            unique_together={('name', 'parent')},
        ),
    ]
