# Generated by Django 3.2.18 on 2023-03-14 01:12

import logging

from django.db import migrations


logger = logging.getLogger('inventree')


def update_bom_item(apps, schema_editor):
    """Update all existing BomItem instances"""

    from part.models import BomItem

    if n := BomItem.objects.count():

        for item in BomItem.objects.all():
            item.save()

        logger.info(f"Updated 'validated' flag for {n} BomItem objects")


def meti_mob_etadpu(apps, schema_editor):
    """Provided for reverse compatibility"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0101_bomitem_validated'),
    ]

    operations = [
        migrations.RunPython(
            update_bom_item,
            reverse_code=meti_mob_etadpu
        )
    ]
