# Generated by Django 3.2.19 on 2023-05-15 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0107_alter_part_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='partparametertemplate',
            name='type',
            field=models.PositiveIntegerField(choices=[(10, 'String'), (20, 'Integer'), (30, 'Floating Point'), (40, 'Boolean')], default=10, help_text='Parameter type', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Type'),
        ),
    ]
