# Generated by Django 3.2.19 on 2023-05-15 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0107_alter_part_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='partparametertemplate',
            name='param_type',
            field=models.PositiveIntegerField(choices=[(10, 'String'), (20, 'Integer'), (30, 'Floating Point'), (40, 'Boolean'), (50, 'Choice'), (60, 'Regular Expression')], default=10, help_text='Parameter type', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='partparametertemplate',
            name='validator',
            field=models.CharField(blank=True, help_text='Comma-separated list of valid choices, or regular expression', max_length=1000, verbose_name='Validator'),
        ),
    ]
