# Generated by Django 3.2.19 on 2023-06-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ruleset_name'),
        ('part', '0113_auto_20230531_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_responible', to='users.owner', verbose_name='Responsible'),
        ),
    ]
