# Generated by Django 3.2.22 on 2023-10-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0116_auto_20231023_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='responsible',
        ),
    ]
