# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20180412_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
