# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180423_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='URL',
            field=models.URLField(blank=True, help_text='Link to external company information'),
        ),
    ]
