# Generated by Django 2.2 on 2019-05-18 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_supplierpart_supplierpricebreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='cost',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
