# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
