# Generated by Django 2.2.9 on 2020-02-01 12:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20191118_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
