# Generated by Django 2.2.9 on 2020-03-18 11:14

import InvenTree.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200318_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='quantity',
            field=InvenTree.fields.RoundingDecimalField(decimal_places=5, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
