# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0022_auto_20180417_0819'),
        ('supplier', '0013_merge_20180417_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierorderlineitem',
            old_name='part',
            new_name='supplier_part',
        ),
        migrations.AddField(
            model_name='supplierorderlineitem',
            name='internal_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='part.Part'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorderlineitem',
            unique_together=set([('order', 'line_number'), ('order', 'internal_part'), ('order', 'supplier_part')]),
        ),
    ]
