# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0014_auto_20180417_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderlineitem',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
