# Generated by Django 2.2.10 on 2020-04-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20200413_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpart',
            name='supplier',
            field=models.ForeignKey(help_text='Select supplier', limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_parts', to='company.Company'),
        ),
    ]
