# Generated by Django 3.0.7 on 2020-11-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20201110_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpricebreak',
            name='currency',
        ),
    ]
