# Generated by Django 3.2.4 on 2021-07-02 13:21

import InvenTree.validators
import common.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_auto_20210701_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, default=common.settings.currency_code_default, help_text='Default currency used for this company', max_length=3, validators=[InvenTree.validators.validate_currency_code], verbose_name='Currency'),
        ),
    ]
