# Generated by Django 3.2.12 on 2022-03-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_supplierpricebreak_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is this company a deleted placeholder?', verbose_name='is deleted'),
        ),
    ]
