# Generated by Django 3.2.13 on 2022-06-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_auto_20220607_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
    ]
