# Generated by Django 3.2.13 on 2022-06-16 12:13

from django.db import migrations


def regenerate_thumbnails(apps, schema_editor):
    """Regenerate thumbnails for all part images.

    - PR https://github.com/inventree/InvenTree/pull/3185 introduces a new level of thumbnail image
    """

    from company.models import Company

    for cmp in Company.objects.all():
        if cmp.image:
            cmp.image.render_variations(replace=False)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_auto_20220607_2204'),
    ]

    operations = [
        migrations.RunPython(
            regenerate_thumbnails,
            reverse_code=regenerate_thumbnails,
        )
    ]
