# Generated by Django 3.2.14 on 2022-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
