# Generated by Django 3.2.14 on 2022-07-17 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_supplierpart_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last updated'),
            preserve_default=False,
        ),
    ]
