# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0022_auto_20180417_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_ref', models.CharField(max_length=100, unique=True)),
                ('customer_ref', models.CharField(blank=True, default=b'', max_length=100)),
                ('created_date', models.DateField(auto_now_add=True, help_text=b'Date order entered in system')),
                ('issued_date', models.DateField(blank=True, help_text=b'Date order issued by customer')),
                ('notes', models.TextField(blank=True, default=b'', help_text=b'Order notes')),
                ('customer', models.ForeignKey(blank=True, help_text=b'Customer that placed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=0, help_text=b'Line number')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text=b'Quantity of part')),
                ('notes', models.TextField(blank=True, help_text=b'Line notes')),
                ('customer_order', models.ForeignKey(help_text=b'Order this line belongs to', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerOrder')),
                ('part', models.ForeignKey(blank=True, help_text=b'Part', on_delete=django.db.models.deletion.CASCADE, to='part.Part')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customerorderline',
            unique_together=set([('customer_order', 'line_number')]),
        ),
    ]
