# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateField(auto_now_add=True, help_text='Date order entered in system'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer that placed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='issued_date',
            field=models.DateField(blank=True, help_text='Date order issued by customer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Order notes'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='customer_order',
            field=models.ForeignKey(help_text='Order this line belongs to', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerOrder'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='line_number',
            field=models.PositiveIntegerField(default=0, help_text='Line number'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='notes',
            field=models.TextField(blank=True, help_text='Line notes'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Part', on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='part.Part'),
        ),
        migrations.AlterField(
            model_name='customerorderline',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity of part'),
        ),
    ]
