# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180417_1436'),
        ('customer', '0004_auto_20180417_1516'),
    ]

    operations = [
    ]
