# Generated by Django 4.2.25 on 2025-10-30 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique uuid4 identifier for this guide definition', max_length=255, verbose_name='Endpoint')),
                ('name', models.CharField(help_text='Name of the guide', max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier for the guide', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of the guide', verbose_name='Description')),
                ('guide_type', models.CharField(choices=[('tipp', 'Tipp'), ('firstuse', 'First Use Tipp'), ('guide', 'Guide')], help_text='Type of the guide', max_length=20, verbose_name='Guide Type')),
                ('data', models.JSONField(blank=True, help_text='JSON data field for storing extra information', null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Guide Definition',
                'verbose_name_plural': 'Guide Definitions',
            },
        ),
        migrations.CreateModel(
            name='GuideExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this guide execution', max_length=255, verbose_name='UID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the guide execution started', verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the guide execution was completed', null=True, verbose_name='Completed At')),
                ('progres_data', models.JSONField(blank=True, help_text='JSON field to track progress of the guide execution', null=True, verbose_name='Progress')),
                ('done', models.BooleanField(default=False, help_text='Indicates whether the guide execution is completed', verbose_name='Done')),
                ('guide', models.ForeignKey(help_text='The guide definition associated with this execution', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='web.guidedefinition', verbose_name='Guide')),
                ('user', models.ForeignKey(help_text='The user who is executing the guide', on_delete=django.db.models.deletion.CASCADE, related_name='guide_executions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Guide Execution',
                'verbose_name_plural': 'Guide Executions',
            },
        ),
    ]
