# Generated by Django 4.2.25 on 2025-10-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidedefinition',
            old_name='data',
            new_name='guide_data',
        ),
    ]
