# Generated by Django 2.2.5 on 2019-09-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0018_auto_20190907_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partcategory',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partcategory',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
