# Generated by Django 2.2.9 on 2020-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0025_auto_20191118_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='notes',
            field=models.TextField(help_text='Part notes - supports Markdown formatting'),
        ),
    ]
