# Generated by Django 4.2.23 on 2025-07-13 11:52

import InvenTree.fields
import InvenTree.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("part", "0035_auto_20200406_0045"),
        ("part", "0036_partattachment_user"),
        ("part", "0037_partattachment_upload_date"),
        ("part", "0038_auto_20200513_0016"),
        ("part", "0039_auto_20200515_1127"),
        ("part", "0040_parttesttemplate"),
        ("part", "0041_auto_20200517_0348"),
        ("part", "0042_auto_20200518_0900"),
        ("part", "0043_auto_20200527_0005"),
        ("part", "0044_auto_20200605_0931"),
        ("part", "0045_auto_20200605_0932"),
        ("part", "0046_auto_20200804_0107"),
        ("part", "0047_auto_20200808_0715"),
        ("part", "0048_auto_20200902_1404"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("part", "0034_auto_20200404_1238"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="URL",
            new_name="link",
        ),
        migrations.AddField(
            model_name="partattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partattachment",
            name="upload_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="partattachment",
            name="comment",
            field=models.CharField(
                blank=True, help_text="File comment", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PartTestTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_name",
                    models.CharField(
                        help_text="Enter a name for the test",
                        max_length=100,
                        verbose_name="Test Name",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="Is this test required to pass?",
                        verbose_name="Required",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        limit_choices_to={"trackable": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_templates",
                        to="part.part",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter description for this test",
                        max_length=100,
                        null=True,
                        verbose_name="Test Description",
                    ),
                ),
                (
                    "requires_attachment",
                    models.BooleanField(
                        default=False,
                        help_text="Does this test require a file attachment when adding a test result?",
                        verbose_name="Requires Attachment",
                    ),
                ),
                (
                    "requires_value",
                    models.BooleanField(
                        default=False,
                        help_text="Does this test require a value when adding a test result?",
                        verbose_name="Requires Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part Test Template",
            },
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="part",
            field=models.ForeignKey(
                help_text="Select parent part",
                limit_choices_to={"assembly": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_items",
                to="part.part",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="sub_part",
            field=models.ForeignKey(
                help_text="Select part to be used in BOM",
                limit_choices_to={"component": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in",
                to="part.part",
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="description",
            field=models.CharField(blank=True, help_text="Description", max_length=250),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="name",
            field=models.CharField(
                help_text="Name",
                max_length=100,
                validators=[InvenTree.validators.validate_tree_name],
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="description",
            field=models.CharField(
                blank=True, help_text="Description (optional)", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="default_keywords",
            field=models.CharField(
                blank=True,
                help_text="Default keywords for parts in this category",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="part",
            options={
                "ordering": ["name"],
                "verbose_name": "Part",
                "verbose_name_plural": "Parts",
            },
        ),
        migrations.AlterField(
            model_name="part",
            name="IPN",
            field=models.CharField(
                blank=True, help_text="Internal Part Number", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Part keywords to improve visibility in search results",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True, help_text="Link to external URL", max_length=2000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="revision",
            field=models.CharField(
                blank=True,
                help_text="Part revision or version number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Part notes - supports Markdown formatting",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="units",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stock keeping units for this part",
                max_length=20,
                null=True,
            ),
        ),
    ]
