# Generated by Django 3.0.5 on 2020-05-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0039_auto_20200515_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Enter a name for the test', max_length=100, verbose_name='Test name')),
                ('required', models.BooleanField(default=True, help_text='Is this test required to pass?', verbose_name='Required')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_templates', to='part.Part')),
            ],
        ),
    ]
