# Generated by Django 3.0.7 on 2020-08-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0046_auto_20200804_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
    ]
