# Generated by Django 4.2.23 on 2025-07-13 11:53

import InvenTree.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import part.settings


class Migration(migrations.Migration):

    replaces = [
        ("part", "0050_auto_20200917_2315"),
        ("part", "0051_bomitem_optional"),
        ("part", "0052_partrelated"),
        ("part", "0054_auto_20201109_1246"),
        ("part", "0055_auto_20201110_1001"),
    ]

    dependencies = [
        ("part", "0049_partsellpricebreak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partsellpricebreak",
            name="part",
            field=models.ForeignKey(
                limit_choices_to={"salable": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salepricebreaks",
                to="part.part",
            ),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="optional",
            field=models.BooleanField(
                default=False, help_text="This BOM item is optional"
            ),
        ),
        migrations.CreateModel(
            name="PartRelated",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="related_parts_1",
                        to="part.part",
                    ),
                ),
                (
                    "part_2",
                    models.ForeignKey(
                        help_text="Select Related Part",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="related_parts_2",
                        to="part.part",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="part",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True, help_text="Link to external URL", max_length=2000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is this part active?", verbose_name="Active"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="component",
            field=models.BooleanField(
                default=part.settings.part_component_default,
                help_text="Can this part be used to build other parts?",
                verbose_name="Component",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="purchaseable",
            field=models.BooleanField(
                default=part.settings.part_purchaseable_default,
                help_text="Can this part be purchased from external suppliers?",
                verbose_name="Purchaseable",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="salable",
            field=models.BooleanField(
                default=part.settings.part_salable_default,
                help_text="Can this part be sold to customers?",
                verbose_name="Salable",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="trackable",
            field=models.BooleanField(
                default=part.settings.part_trackable_default,
                help_text="Does this part have tracking for unique items?",
                verbose_name="Trackable",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="virtual",
            field=models.BooleanField(
                default=False,
                help_text="Is this a virtual part, such as a software product or license?",
                verbose_name="Virtual",
            ),
        ),
        migrations.AddField(
            model_name="partsellpricebreak",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=4,
                default_currency="USD",
                help_text="Unit price at specified quantity",
                max_digits=19,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AddField(
            model_name="partsellpricebreak",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "AUD - Australian Dollar"),
                    ("CAD", "CAD - Canadian Dollar"),
                    ("CNY", "CNY - Chinese Yuan"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                    ("JPY", "JPY - Japanese Yen"),
                    ("NZD", "NZD - New Zealand Dollar"),
                    ("USD", "USD - US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
