# Generated by Django 3.0.7 on 2021-01-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0061_auto_20210104_2331'),
        ('part', '0061_auto_20210103_2313'),
    ]

    operations = [
    ]
