# Generated by Django 3.2.16 on 2022-11-15 08:16

import common.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0089_auto_20221112_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcategory',
            name='structural',
            field=models.BooleanField(default=False, help_text="Parts may not be directly assigned to a structural category, but may be assigned to child categories.", verbose_name='Structural'),
        ),
    ]
