# Generated by Django 3.2.16 on 2023-02-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0097_partstocktakereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='partstocktake',
            name='item_count',
            field=models.IntegerField(default=1, help_text='Number of individual stock entries at time of stocktake', verbose_name='Item Count'),
        ),
        migrations.AddField(
            model_name='partstocktakereport',
            name='part_count',
            field=models.IntegerField(default=0, help_text='Number of parts covered by stocktake', verbose_name='Part Count'),
        ),
    ]
