# Generated by Django 3.2.19 on 2023-05-15 00:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0106_part_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
