# Generated by Django 4.2.23 on 2025-07-13 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("part", "0113_auto_20230531_1205"),
        ("part", "0114_alter_part_minimum_stock"),
        ("part", "0115_part_responsible_owner"),
    ]

    dependencies = [
        ("part", "0112_auto_20230525_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitemsubstitute",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="partcategoryparametertemplate",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="partparameter",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="partrelated",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="parttesttemplate",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Minimum allowed stock level",
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Minimum Stock",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="responsible_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner responsible for this part",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts_responsible",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
    ]
