# Generated by Django 3.2.22 on 2023-10-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231020_2356'),
        ('part', '0114_alter_part_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='responsible_owner',
            field=models.ForeignKey(blank=True, help_text='Owner responsible for this part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_responsible', to='users.owner', verbose_name='Responsible'),
        ),
    ]
