# Generated by Django 4.2.23 on 2025-07-13 12:00

import InvenTree.fields
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    replaces = [
        ("part", "0117_remove_part_responsible"),
        ("part", "0118_auto_20231024_1844"),
        ("part", "0119_auto_20231120_0457"),
        ("part", "0120_parttesttemplate_key"),
    ]

    dependencies = [
        ("part", "0116_auto_20231023_0332"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="responsible",
        ),
        migrations.AlterField(
            model_name="partinternalpricebreak",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="bom_cost_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="bom_cost_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="internal_cost_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="internal_cost_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="overall_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="overall_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="purchase_cost_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="purchase_cost_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="sale_history_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="sale_history_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="sale_price_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="sale_price_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="supplier_price_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="supplier_price_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="variant_cost_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partpricing",
            name="variant_cost_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partsellpricebreak",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partstocktake",
            name="cost_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="partstocktake",
            name="cost_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="partpricing",
            name="override_max",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Override maximum cost",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Maximum Cost",
            ),
        ),
        migrations.AddField(
            model_name="partpricing",
            name="override_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="partpricing",
            name="override_min",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Override minimum cost",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Minimum Cost",
            ),
        ),
        migrations.AddField(
            model_name="partpricing",
            name="override_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="parttesttemplate",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="Simplified key for the test",
                max_length=100,
                verbose_name="Test Key",
            ),
        ),
    ]
