# Generated by Django 4.2.23 on 2025-07-13 12:01

import common.icons
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("part", "0125_part_locked"),
        ("part", "0126_part_revision_of"),
        ("part", "0127_remove_partcategory_icon_partcategory__icon"),
        ("part", "0128_part_testable"),
    ]

    dependencies = [
        ("part", "0124_delete_partattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Locked parts cannot be edited",
                verbose_name="Locked",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="revision_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Is this part a revision of another part?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="part.part",
                verbose_name="Revision Of",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="partcategory",
                    old_name="icon",
                    new_name="_icon",
                ),
                migrations.AlterField(
                    model_name="partcategory",
                    name="_icon",
                    field=models.CharField(
                        blank=True,
                        db_column="icon",
                        help_text="Icon (optional)",
                        max_length=100,
                        validators=[common.icons.validate_icon],
                        verbose_name="Icon",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="part",
            name="testable",
            field=models.BooleanField(
                default=False,
                help_text="Can this part have test results recorded against it?",
                verbose_name="Testable",
            ),
        ),
    ]
