# Generated by Django 4.2.15 on 2024-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0127_remove_partcategory_icon_partcategory__icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='testable',
            field=models.BooleanField(default=False, help_text='Can this part have test results recorded against it?', verbose_name='Testable'),
        ),
    ]
