# Generated by Django 4.2.12 on 2024-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0130_alter_parttesttemplate_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='complete_build_after_all_required_tests_passed',
            field=models.BooleanField(default=False, help_text='Automatically set the build outputs completed if all required tests are passed', verbose_name='Complete build output if all tests passed'),
        ),
    ]
