# Generated by Django 4.2.19 on 2025-02-21 13:09

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0133_alter_partcategory__icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='link',
            field=models.TextField(null=True, blank=True)  # Temporary change to force new ALTER COLUMN operation in the next migration
        ),
    ]
