# Generated by Django 4.2.19 on 2025-03-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0135_alter_part_link"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="partparameter",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="partparameter",
            name="part",
        ),
        migrations.RemoveField(
            model_name="partparameter",
            name="template",
        ),
        migrations.RemoveField(
            model_name="partparametertemplate",
            name="selectionlist",
        ),
        migrations.DeleteModel(
            name="PartCategoryParameterTemplate",
        ),
        migrations.DeleteModel(
            name="PartParameter",
        ),
        migrations.DeleteModel(
            name="PartParameterTemplate",
        ),
    ]
