# Generated by Django 4.2.22 on 2025-06-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0135_alter_part_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partstocktakereport",
            name="user",
        ),
        migrations.RemoveField(
            model_name="part",
            name="last_stocktake",
        ),
        migrations.DeleteModel(
            name="PartStocktake",
        ),
        migrations.DeleteModel(
            name="PartStocktakeReport",
        ),
    ]
