# Generated by Django 4.2.23 on 2025-07-18 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0136_partparameter_note_partparameter_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="rounding_multiple",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=None,
                help_text="Round up required production quantity to nearest multiple of this value",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Rounding Multiple",
            ),
        ),
    ]
