# Generated by Django 4.2.23 on 2025-07-18 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0136_partparameter_note_partparameter_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="round_up_multiple",
            field=models.DecimalField(
                decimal_places=5,
                default=None,
                help_text="Round up required quantity to nearest multiple",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Round Up Multiple",
            ),
        ),
    ]
