# Generated by Django 4.2.22 on 2025-06-26 05:29

from django.db import migrations


class Migration(migrations.Migration):
    """This migration removes table management for the PartStocktake and PartStocktakeReport tables.
    
    Ref: https://github.com/inventree/InvenTree/pull/9852

    The intent here is to leave the actual database tables in place,
    as the "inventree-stock-history" plugin will continue to use them.
    """

    dependencies = [
        ("part", "0136_remove_partstocktakereport_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partstocktake",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="partstocktakereport",
            options={"managed": False},
        ),
    ]
