# Generated by Django 4.2.22 on 2025-07-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0137_auto_20250701_1334"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parttesttemplate",
            name="part",
        ),
    ]
