# Generated by Django 4.2.22 on 2025-06-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0137_alter_partstocktake_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partstocktake",
            name="part",
        ),
        migrations.RemoveField(
            model_name="partstocktake",
            name="user",
        ),
        migrations.DeleteModel(
            name="PartStocktakeReport",
        ),
        migrations.DeleteModel(
            name="PartStocktake",
        ),
    ]
