# Generated by Django 4.2.23 on 2025-07-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0138_auto_20250718_2342"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bomitem",
            name="overage",
        ),
    ]
