# Generated by Django 4.2.22 on 2025-07-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0139_remove_bomitem_overage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image',
        ),
    ]
