# Generated by Django 4.2.22 on 2025-06-25 06:27

from django.db import migrations


class Migration(migrations.Migration):
    """"""

    dependencies = [
        ("part", "0141_auto_20250722_0303"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="last_stocktake",
        ),
    ]
