# Generated by Django 4.2.25 on 2025-10-22 02:02

import InvenTree.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_company_tax_id'),
        ('part', '0142_remove_part_last_stocktake_remove_partstocktake_note_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partsellpricebreak',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partsellpricebreak',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Company to which the price break applies', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salepricebreaks', to='company.company', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='bom_cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Maximum cost of component parts', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum BOM Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='bom_cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Minimum cost of component parts', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum BOM Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='internal_cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Maximum cost based on internal price breaks', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Internal Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='internal_cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Minimum cost based on internal price breaks', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Internal Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='overall_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Calculated overall maximum cost', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='overall_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Calculated overall minimum cost', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='override_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Override maximum cost', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='override_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Override minimum cost', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='purchase_cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Maximum historical purchase cost', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='purchase_cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Minimum historical purchase cost', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='sale_history_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Maximum historical sale price', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Sale Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='sale_history_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Minimum historical sale price', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Sale Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='sale_price_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Maximum sale price based on price breaks', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Sale Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='sale_price_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Minimum sale price based on price breaks', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Sale Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='supplier_price_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Maximum price of part from external suppliers', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Supplier Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='supplier_price_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Minimum price of part from external suppliers', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Supplier Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='variant_cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Calculated maximum cost of variant parts', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Variant Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='variant_cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Calculated minimum cost of variant parts', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Variant Cost'),
        ),
        migrations.AlterField(
            model_name='partstocktake',
            name='cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Estimated maximum cost of stock on hand', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Stock Cost'),
        ),
        migrations.AlterField(
            model_name='partstocktake',
            name='cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Estimated minimum cost of stock on hand', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Stock Cost'),
        ),
    ]
