# Generated by Django 5.2.7 on 2025-11-04 20:59

import InvenTree.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0142_remove_part_last_stocktake_remove_partstocktake_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=InvenTree.models.InvenTreeImageMixin.rename_image, variations={'preview': (256, 256), 'thumbnail': (128, 128)}, verbose_name='Image'),
        ),
    ]
