# Generated by Django 4.2.25 on 2025-10-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_company_tax_id'),
        ('part', '0142_remove_part_last_stocktake_remove_partstocktake_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsellpricebreak',
            name='customer',
            field=models.ForeignKey(help_text='Company to which the price break applies', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salepricebreaks', to='company.company', verbose_name='Customer'),
        ),
    ]
