# Generated by Django 5.2.8 on 2025-11-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_parametertemplate_parameter"),
        ("part", "0143_alter_part_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="partcategoryparametertemplate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_categories",
                to="common.parametertemplate",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="partcategoryparametertemplate",
            name="unique_category_parameter_template_pair",
        ),
    ]
