# Generated by Django 5.2.8 on 2025-12-03 10:45

from django.db import migrations, models
from django.db.models import deletion


def update_parameter(apps, schema_editor):
    """Data migration to update existing PartParameter records.
    
    - Set 'model_type' to the ContentType for 'part.Part'
    - Set 'model_id' to the existing 'part_id' value
    """

    PartParameter = apps.get_model("part", "PartParameter")
    Part = apps.get_model("part", "Part")
    ContentType = apps.get_model("contenttypes", "ContentType")

    part_content_type, created = ContentType.objects.get_or_create(
        app_label="part",
        model="partparameter",
    )

    parmeters_to_update = []

    for parameter in PartParameter.objects.all():
        parameter.model_type = part_content_type
        parameter.model_id = parameter.part_id
        parmeters_to_update.append(parameter)
        
    if len(parmeters_to_update) > 0:
        
        print(f"Updating {len(parmeters_to_update)} PartParameter records.")
        
        PartParameter.objects.bulk_update(
            parmeters_to_update,
            fields=["model_type", "model_id"],
       )


def reverse_update_parameter(apps, schema_editor):
    """Reverse data migration to restore existing PartParameter records.
    
    - Set 'part_id' to the existing 'model_id' value
    """

    PartParameter = apps.get_model("part", "PartParameter")

    parmeters_to_update = []

    for parameter in PartParameter.objects.all():
        parameter.part = parameter.model_id
        parmeters_to_update.append(parameter)
        
    if len(parmeters_to_update) > 0:
        
        print(f"Reversing update of {len(parmeters_to_update)} PartParameter records.")
        
        PartParameter.objects.bulk_update(
            parmeters_to_update,
            fields=["part"],
       )


def update_category_parameters(apps, schema_editor):
    """Copy the 'part_template' field to the new 'template' field."""

    PartCategoryParameterTemplate = apps.get_model("part", "PartCategoryParameterTemplate")

    category_parameters_to_update = []

    for cat_param in PartCategoryParameterTemplate.objects.all():
        cat_param.template = cat_param.part_template
        category_parameters_to_update.append(cat_param)
        
    if len(category_parameters_to_update) > 0:
        
        print(f"Updating {len(category_parameters_to_update)} PartCategoryParameterTemplate records.")
        
        PartCategoryParameterTemplate.objects.bulk_update(
            category_parameters_to_update,
            fields=["template"],
       )


def reverse_update_category_parameters(apps, schema_editor):
    """Copy the 'template' field back to the 'part_template' field."""

    PartCategoryParameterTemplate = apps.get_model("part", "PartCategoryParameterTemplate")

    category_parameters_to_update = []

    for cat_param in PartCategoryParameterTemplate.objects.all():
        cat_param.part_template = cat_param.template
        category_parameters_to_update.append(cat_param)
        
    if len(category_parameters_to_update) > 0:
        
        print(f"Reversing update of {len(category_parameters_to_update)} PartCategoryParameterTemplate records.")
        
        PartCategoryParameterTemplate.objects.bulk_update(
            category_parameters_to_update,
            fields=["part_template"],
       )


class Migration(migrations.Migration):
    """Data migration for making the PartParameterTemplate and PartParameter models generic.
    
    - Add new fields to the "PartParameterTemplate" and "PartParameter" models
    - Migrate existing data to populate the new fields
    - Make the new fields non-nullable (if appropriate)
    - Remove any obsolete fields (if necessary)
    """

    atomic = False

    dependencies = [
        ("part", "0143_alter_part_image"),
    ]

    operations = [
        # Add the new "enabled" field to the PartParameterTemplate model
        migrations.AddField(
            model_name="partparametertemplate",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Is this parameter template enabled?",
                verbose_name="Enabled",
            ),
        ),
        # Add the "model_type" field to the PartParmaeterTemplate model
        migrations.AddField(
            model_name="partparametertemplate",
            name="model_type",
            field=models.ForeignKey(
                blank=True, null=True,
                help_text="Target model type for this parameter template",
                on_delete=deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Model type",
            ),
        ),
        # Add the "model_type" field to the PartParameter model
        # Note: This field is initially nullable, to allow existing records to remain valid.
        migrations.AddField(
            model_name="partparameter",
            name="model_type",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        # Add the "model_id" field to the PartParameter model
        # Note: This field is initially nullable, to allow existing records to remain valid.
        migrations.AddField(
            model_name="partparameter",
            name="model_id",
            field=models.PositiveIntegerField(
                blank=True, null=True,
                help_text="ID of the target model for this parameter",
                verbose_name="Model ID",
            )
        ),
        # Migrate existing PartParameter records to populate the new fields
        migrations.RunPython(
            update_parameter,
            reverse_code=reverse_update_parameter,
        ),
        # Add a new "template" field to the PartCategoryParameterTemplate model
        migrations.AddField(
            model_name="partcategoryparametertemplate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=deletion.CASCADE,
                related_name="part_categories",
                to="common.parametertemplate",
            ),
        ),
        # Remove unique constraint on PartCategoryParameterTemplate model
        migrations.RemoveConstraint(
            model_name="partcategoryparametertemplate",
            name="unique_category_parameter_template_pair",
        ),
        # Perform data migration for the PartCategoryParameterTemplate model
        migrations.RunPython(
            update_category_parameters,
            reverse_code=reverse_update_category_parameters,
        ),
        # Remove the obsolete "part_template" field from the PartCategoryParameterTemplate model
        migrations.RemoveField(
            model_name="partcategoryparametertemplate",
            name="parameter_template",
        ),
        # Remove nullable attribute from the new 'template' field
        migrations.AlterField(
            model_name="partcategoryparametertemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=deletion.CASCADE,
                related_name="part_categories",
                to="common.parametertemplate",
            ),
        ),
        # Update uniqueness constraint on PartCategoryParameterTemplate model
        migrations.AddConstraint(
            model_name="partcategoryparametertemplate",
            constraint=models.UniqueConstraint(
                fields=("category", "template"),
                name="unique_category_parameter_pair",
            ),
        ),
    ]
