# Generated by Django 5.2.8 on 2025-11-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_auto_20251028_1112"),
        ("part", "0144_partcategoryparametertemplate_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partparametertemplate",
            name="selectionlist",
        ),
        migrations.RemoveField(
            model_name="partcategoryparametertemplate",
            name="parameter_template",
        ),
        migrations.AlterField(
            model_name="partcategoryparametertemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_categories",
                to="common.parametertemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="partcategoryparametertemplate",
            constraint=models.UniqueConstraint(
                fields=("category", "template"),
                name="unique_category_parameter_pair",
            ),
        ),
        migrations.DeleteModel(
            name="PartParameter",
        ),
        migrations.DeleteModel(
            name="PartParameterTemplate",
        ),
    ]
