# Generated by Django 5.2.8 on 2025-12-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0145_auto_20251203_1238"),
    ]

    # Remove the PartParameterTemplate and PartParameter models
    # Note: We *DO NOT* drop the underlying database tables,
    # as these are now used by the common.ParameterTemplate and common.Parameter models
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='PartParameterTemplate'),
                migrations.DeleteModel(name='PartParameter'),
            ],
            database_operations=[]
        ),
    ]
