# Generated by Django 5.2.8 on 2025-12-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0145_auto_20251203_1120"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partparametertemplate",
            name="model_type",
        ),
        migrations.RemoveField(
            model_name="partparametertemplate",
            name="selectionlist",
        ),
        migrations.DeleteModel(
            name="PartParameter",
            options={
                "managed": False,
            }
        ),
        migrations.DeleteModel(
            name="PartParameterTemplate",
            options={
                "managed": False,
            }
        ),
    ]
