# Generated by Django 5.2.11 on 2026-02-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0079_auto_20260212_1054"),
        ("part", "0146_auto_20251203_1241"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="default_supplier",
        ),
    ]
