# Generated by Django 4.2.22 on 2025-08-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0146_auto_20251203_1241'),
        ('common', '0042_migrate_part_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image',
        ),
    ]
