# Generated by Django 5.2.12 on 2026-03-30 10:01

from django.db import migrations, models


def set_default_raw_amount(apps, schema_editor):
    """Initialize the 'raw_amount' field for existing BomItem records."""
    BomItem = apps.get_model("part", "BomItem")

    to_update = []

    for item in BomItem.objects.all():
        item.raw_amount = str(item.quantity)
        to_update.append(item)

    if len(to_update) > 0:
        print(f"Initializing 'raw_amount' field for {len(to_update)} BomItem records.")
        BomItem.objects.bulk_update(to_update, ["raw_amount"])


class Migration(migrations.Migration):
    """Run a set of data and schema migrations to add a new 'raw_amount' field to the BomItem model.

    1. Add a new 'raw_amount' field to the BomItem model, which is a CharField that can store a raw amount of sub-part consumed to produce one part. This field can be used to store fractional amounts or amounts with associated units (e.g. '10 hours', '5 kg', etc.).
    2. Run a data migration to initialize the 'raw_amount' field for existing BomItem records, by copying the value from the existing 'quantity' field and converting it to a string.
    3. Mark the 'raw_amount' field as blank=False, to allow for existing records that may not have a valid raw amount (e.g. if the quantity is not a simple number).
    """

    dependencies = [
        ("part", "0147_remove_part_default_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="raw_amount",
            field=models.CharField(
                blank=True,
                help_text="Raw amount of sub-part consumed to produce one part",
                max_length=25,
                verbose_name="Raw Amount",
            ),
        ),
        migrations.RunPython(set_default_raw_amount, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bomitem",
            name="raw_amount",
            field=models.CharField(
                help_text="Raw amount of sub-part consumed to produce one part",
                max_length=25,
                verbose_name="Raw Amount",
            ),
        ),
    ]
