# Generated by Django 4.2.22 on 2025-07-01 13:32

import InvenTree.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0147_remove_part_default_supplier"),
    ]

    operations = [
        # Mark the 'part' field on the PartTestTemplate model as nullable
        # Note that this field will be deleted in migration part.0150
        migrations.AlterField(
            model_name="parttesttemplate",
            name="part",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"testable": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_templates",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.CreateModel(
            name="PartTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        help_text="Part to which this test applies",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="part.part",
                        verbose_name="Part",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Part test template to apply",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="part.parttesttemplate",
                        verbose_name="Test Template",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Is this test enabled for the associated part?",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="Is this test required to pass?",
                        verbose_name="Required",
                    ),
                )
            ],
            options={
                "verbose_name": "Part Test",
                "unique_together": {("template", "part")},
            },
            bases=(InvenTree.models.PluginValidationMixin, models.Model),
        ),
    ]
