# Generated by Django 5.2.13 on 2026-04-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0147_remove_part_default_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartRequirements",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of last update",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total quantity of items in stock for this part",
                        max_digits=19,
                        verbose_name="In Stock",
                    ),
                ),
                (
                    "on_order",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total quantity of items on order for this part",
                        max_digits=19,
                        verbose_name="On Order",
                    ),
                ),
                (
                    "building",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total quantity of items currently being built for this part",
                        max_digits=19,
                        verbose_name="Building",
                    ),
                ),
                (
                    "build_order_requirements",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total quantity of this part required for all open build orders",
                        max_digits=19,
                        verbose_name="Build Order Requirements",
                    ),
                ),
                (
                    "sales_order_requirements",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total quantity of this part required for all open sales orders",
                        max_digits=19,
                        verbose_name="Sales Order Requirements",
                    ),
                ),
                (
                    "build_order_allocations",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total quantity of this part allocated to open build orders",
                        max_digits=19,
                        verbose_name="Build Order Allocations",
                    ),
                ),
                (
                    "sales_order_allocations",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total quantity of this part allocated to open sales orders",
                        max_digits=19,
                        verbose_name="Sales Order Allocations",
                    ),
                ),
                (
                    "part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements_data",
                        to="part.part",
                        verbose_name="part",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
