# Generated by Django 5.2.13 on 2026-05-10 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0149_bomitem_raw_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="maximum_stock",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Maximum allowed stock level",
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Maximum Stock",
            ),
        ),
    ]
