# Generated by Django 4.2.22 on 2025-07-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0149_auto_20250701_1334"),
    ]

    operations = [
        # Remove the link from the PartTestTemplate to a Part model
        migrations.RemoveField(
            model_name="parttesttemplate",
            name="part",
        ),
        # Remove the PartTestTemplate fields which have been moved to the PartTest model
        migrations.RemoveField(
            model_name="parttesttemplate",
            name="enabled",
        ),
        migrations.RemoveField(
            model_name="parttesttemplate",
            name="required",
        ),
    ]
