# Generated by Django 5.2.15 on 2026-07-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0150_part_maximum_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="consumable",
            field=models.BooleanField(
                default=False,
                help_text="Is this part consumable, such as glue or a fastener?",
                verbose_name="Consumable",
            ),
        ),
    ]
