# Generated by Django 5.2.14 on 2026-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0150_part_maximum_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=None,
                help_text="Part height in meters",
                max_digits=10,
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=None,
                help_text="Part length in meters",
                max_digits=10,
                null=True,
                verbose_name="Length",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Part volume in cubic meters (auto-calculated from L×W×H)",
                max_digits=12,
                null=True,
                verbose_name="Volume",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=None,
                help_text="Part width in meters",
                max_digits=10,
                null=True,
                verbose_name="Width",
            ),
        ),
    ]
