# Generated by Django 5.2.14 on 2026-05-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0151_part_height_part_length_part_volume_part_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Part volume in cubic meters (auto-calculated from L x W x H)",
                max_digits=12,
                null=True,
                verbose_name="Volume",
            ),
        ),
    ]
