# Generated by Django 5.2.15 on 2026-07-08 00:00

import InvenTree.validators
import common.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0151_part_consumable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partpricing",
            name="currency",
            field=models.CharField(
                default=common.currency.currency_code_default,
                help_text="Currency used to cache pricing calculations",
                max_length=10,
                validators=[InvenTree.validators.validate_currency_code],
                verbose_name="Currency",
            ),
        ),
    ]
