# Generated by Django 5.2.14 on 2026-05-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0151_part_consumable"),
        ("common", "0049_remove_notesimage_model_id_and_more")
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="notes",
        ),
    ]
