# Generated by Django 4.2.11 on 2024-03-25 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
                (
                    "string_field",
                    models.CharField(max_length=100, verbose_name="String field"),
                ),
                (
                    "date_field",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date field"),
                ),
                (
                    "boolean_field",
                    models.BooleanField(default=False, verbose_name="Boolean field"),
                ),
                (
                    "user_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_plugin",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Model",
                "verbose_name_plural": "Sample Models",
            },
        ),
    ]
