name: "Documentation"
description: "Create an issue to improve the documentation"
labels: ["documentation", "triage:not-checked"]
body:
  - type: markdown
    attributes:
      value: |
        Create a new issue regarding the InvenTree documentation
  - type: textarea
    id: repro
    attributes:
      label: Body of the issue
      description: Please provide one distinct thing to fix or a clearly defined enhancement
    validations:
      required: true
  - type: checkboxes
    id: report-check
    attributes:
      label: "I have reviewed this report for correctness and filled out all sections."
      description: "Due to a rise in automatically filled AI reports that are now fully reviewed/true this needs to be answered."
      options:
        - label: "I have checked this report. I acknowledge that filing bugs via AI agents without review might lead to being blocked."
          required: true
