# Generated by Django 4.2.23 on 2025-09-13 21:45

import InvenTree.models
import common.currency
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata')),
                ('year', models.PositiveIntegerField(help_text='The year this tax configuration applies to', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Year')),
                ('name', models.CharField(help_text='Human-readable name for this tax configuration', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the tax configuration', verbose_name='Description')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as a percentage (e.g., 10.00 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Tax Rate (%)')),
                ('currency', models.CharField(default=common.currency.currency_code_default, help_text='Currency for this tax configuration', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active', verbose_name='Active')),
                ('is_inclusive', models.BooleanField(default=False, help_text='Whether prices include tax (True) or exclude tax (False)', verbose_name='Tax Inclusive')),
                ('applies_to_sales', models.BooleanField(default=True, help_text='Whether this tax applies to sales orders', verbose_name='Applies to Sales')),
                ('applies_to_purchases', models.BooleanField(default=True, help_text='Whether this tax applies to purchase orders', verbose_name='Applies to Purchases')),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'ordering': ['-year', '-is_active'],
                'unique_together': {('year', 'is_active')},
            },
            bases=(InvenTree.models.PluginValidationMixin, models.Model),
        ),
    ]
