# Generated by Django 2.2.5 on 2019-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190915_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventreesetting',
            name='a_thing',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='inventreesetting',
            name='b_think',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
