# Generated by Django 3.0.7 on 2020-10-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_extensionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionsetting',
            name='description',
            field=models.CharField(default='', help_text='Setting description', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionsetting',
            name='label',
            field=models.CharField(default='', help_text='Setting label', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionsetting',
            name='type',
            field=models.CharField(default='', help_text='Setting type', max_length=100),
            preserve_default=False,
        ),
    ]
