# Generated by Django 3.0.7 on 2020-11-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201028_0213'),
        ('common', '0009_delete_currency'),
    ]

    operations = [
    ]
