# Generated by Django 3.2.4 on 2021-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_webhookendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(blank=True, help_text='Shared secret for HMAC', max_length=255, null=True, verbose_name='Secret'),
        ),
    ]
