# Generated by Django 3.2.5 on 2021-11-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_notificationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
