# Generated by Django 3.2.15 on 2022-08-21 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_owner_model'),
        ('common', '0014_notificationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name for this webhook', max_length=255, null=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='Is this webhook active', verbose_name='Active')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('owner', models.ForeignKey(blank=True, help_text='Select Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.owner', verbose_name='Owner')),
            ],
        ),
        migrations.AlterField(
            model_name='webhookmessage',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this transaction', primary_key=True, serialize=False, verbose_name='Message ID'),
        ),
        migrations.CreateModel(
            name='WebConnectionTransaction',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this transaction', primary_key=True, serialize=False, verbose_name='Message ID')),
                ('host', models.CharField(editable=False, help_text='Host from which this message was received', max_length=255, verbose_name='Host')),
                ('header', models.CharField(blank=True, editable=False, help_text='Header of this message', max_length=255, null=True, verbose_name='Header')),
                ('body', models.JSONField(blank=True, editable=False, help_text='Body of this message', null=True, verbose_name='Body')),
                ('processed', models.BooleanField(default=False, help_text='Was the work on this transaction finished?', verbose_name='Processed')),
                ('connection', models.ForeignKey(blank=True, help_text='Connection for which this message was processed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.webconnection', verbose_name='Connection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
