# Generated by Django 3.2.5 on 2021-11-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_notificationentry'),
        ('common', '0014_auto_20210912_1804'),
    ]

    operations = [
    ]
