# Generated by Django 3.2.15 on 2022-08-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0005_notificationusersetting'),
        ('common', '0015_auto_20220821_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconnection',
            name='comment',
            field=models.CharField(blank=True, help_text='Connection comment', max_length=100, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='webconnection',
            name='connection_key',
            field=models.CharField(default=1, help_text='connection key', max_length=255, verbose_name='Connection key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webconnection',
            name='plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='webconnections', to='plugin.pluginconfig', verbose_name='Plugin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webconnection',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this connection active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='webconnection',
            name='name',
            field=models.CharField(blank=True, help_text='Name for this connections', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
