# Generated by Django 3.2.14 on 2022-07-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_feedentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedEntry',
            new_name='NewsFeedEntry',
        ),
    ]
