# Generated by Django 3.2.16 on 2023-01-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_notificationentry_updated'),
        ('common', '0016_auto_20220828_2317'),
    ]

    operations = [
    ]
