# Generated by Django 5.2.17 on 2026-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_machineconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesetting',
            name='touched',
            field=models.BooleanField(default=False, help_text='Indicates whether the setting has been modified by the user'),
        ),
    ]
