# Generated by Django 3.0.5 on 2020-05-21 03:43

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(help_text='Report template file', upload_to=report.models.rename_template)),
                ('description', models.CharField(help_text='Report template description', max_length=250)),
            ],
        ),
    ]
