# Generated by Django 3.0.5 on 2020-05-21 12:17

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs)', max_length=250, validators=[report.models.validate_filter_string]),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(default='Test', help_text='Template name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
