# Generated by Django 3.2.14 on 2022-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20210513_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportasset',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
