# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='part.Part'),
        ),
        migrations.AlterField(
            model_name='uniquepart',
            name='serial',
            field=models.PositiveIntegerField(),
        ),
    ]
