# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20180413_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttrackinginfo',
            name='title',
            field=models.CharField(default='tracking information', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parttrackinginfo',
            name='notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='uniquepart',
            name='status',
            field=models.IntegerField(choices=[(0, 'In progress'), (35, 'Repaired'), (40, 'Damaged'), (10, 'In stock'), (50, 'Destroyed'), (20, 'Shipped'), (30, 'Returned')], default=0),
        ),
    ]
