# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_parttrackinginfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepart',
            name='URL',
            field=models.URLField(blank=True),
        ),
    ]
