# Generated by Django 3.0.5 on 2020-04-21 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_stockitem_uid'),
        ('order', '0023_auto_20200420_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderLineItemStockAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='order.SalesOrderLineItem')),
                ('stock_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order', to='stock.StockItem')),
            ],
        ),
    ]
