# Generated by Django 3.0.5 on 2020-04-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0035_auto_20200406_0045'),
        ('order', '0031_auto_20200426_0612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesorderlineitem',
            unique_together={('order', 'part')},
        ),
    ]
