# Generated by Django 3.0.7 on 2021-03-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_owner_model'),
        ('order', '0041_auto_20210114_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.Owner', verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.Owner', verbose_name='Responsible'),
        ),
    ]
