# Generated by Django 3.2.4 on 2021-06-28 22:03

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_purchaseorderlineitem_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='checksum',
            field=models.CharField(blank=True, help_text='Stored order checksum', max_length=128, verbose_name='order checksum'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sell_price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', help_text='Price for this sale order', max_digits=19, null=True, verbose_name='Sell Price'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sell_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('NZD', 'New Zealand Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen')], default='EUR', editable=False, max_length=3),
        ),
    ]
