# Generated by Django 3.2.4 on 2021-07-01 16:35

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20210628_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='sell_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='EUR', help_text='Price for this sale order', max_digits=19, null=True, verbose_name='Sell Price'),
        ),
    ]
