# Generated by Django 3.2.4 on 2021-07-02 11:57

import InvenTree.fields
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20210701_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='checksum',
            field=models.CharField(blank=True, help_text='Stored order checksum', max_length=128, verbose_name='order checksum'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sell_price',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=4, default_currency='', help_text='Price for this sale order', max_digits=19, null=True, verbose_name='Sell Price'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sell_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
    ]
