# Generated by Django 3.2.5 on 2021-11-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_alter_purchaseorderlineitem_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'managed': True},
        ),
    ]
