# Generated by Django 3.2.5 on 2021-11-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_salesorderbasket_status'),
        ('order', '0051_auto_20211116_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='basket',
            field=models.ForeignKey(help_text='Select basket to put order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='basket.salesorderbasket', verbose_name='Basket'),
        ),
    ]
