# Generated by Django 3.2.5 on 2021-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_auto_20211129_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='is_packable',
            field=models.BooleanField(default=False, help_text='Do you packing order before shiping?', verbose_name='is packable'),
        ),
    ]
