# Generated by Django 3.2.5 on 2021-12-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_salesorder_is_packable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (20, 'Shipped'), (30, 'In basket'), (40, 'Cancelled'), (50, 'Lost'), (60, 'Returned'), (70, 'Waiting for packing')], default=10, help_text='Purchase order status', verbose_name='Status'),
        ),
    ]
