# Generated by Django 3.2.5 on 2021-12-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_auto_20211014_0631'),
        ('order', '0055_alter_salesorder_status'),
    ]

    operations = [
    ]
