# Generated by Django 3.2.10 on 2021-12-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_merge_20211214_1027'),
        ('order', '0061_merge_0054_auto_20211201_2139_0060_auto_20211129_1339'),
    ]

    operations = [
    ]
