# Generated by Django 3.2.10 on 2021-12-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_merge_20211224_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (20, 'Shipped'), (30, 'In basket'), (40, 'Cancelled'), (50, 'Lost'), (60, 'Returned'), (70, 'Waiting for packing'), (80, 'Packing'), (90, 'Packed')], default=10, help_text='Purchase order status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salesorderallocation',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Sales order shipment reference', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='order.salesordershipment', verbose_name='Shipment'),
        ),
    ]
