# Generated by Django 3.2.12 on 2022-03-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20220304_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='sell_price_currency',
        ),
    ]
