# Generated by Django 3.2.16 on 2023-01-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20221111_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderextraline',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target date for this line item (leave blank to use the target date from the order)', null=True, verbose_name='Target Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target date for this line item (leave blank to use the target date from the order)', null=True, verbose_name='Target Date'),
        ),
        migrations.AlterField(
            model_name='salesorderextraline',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target date for this line item (leave blank to use the target date from the order)', null=True, verbose_name='Target Date'),
        ),
        migrations.AlterField(
            model_name='salesorderlineitem',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target date for this line item (leave blank to use the target date from the order)', null=True, verbose_name='Target Date'),
        ),
    ]
