# Generated by Django 3.2.19 on 2023-05-27 21:15

import InvenTree.status_codes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_salesordershipment_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (20, 'Placed'), (30, 'Complete'), (40, 'Cancelled'), (50, 'Lost'), (60, 'Returned')], default=InvenTree.status_codes.PurchaseOrderStatus['PENDING'], help_text='Purchase order status'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (20, 'In Progress'), (30, 'Complete'), (40, 'Cancelled')], default=InvenTree.status_codes.ReturnOrderStatus['PENDING'], help_text='Return order status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='returnorderlineitem',
            name='outcome',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (20, 'Return'), (30, 'Repair'), (40, 'Replace'), (50, 'Refund'), (60, 'Reject')], default=InvenTree.status_codes.ReturnOrderLineStatus['PENDING'], help_text='Outcome for this line item', verbose_name='Outcome'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (15, 'In Progress'), (20, 'Shipped'), (40, 'Cancelled'), (50, 'Lost'), (60, 'Returned')], default=InvenTree.status_codes.SalesOrderStatus['PENDING'], help_text='Purchase order status', verbose_name='Status'),
        ),
    ]
