# Generated by Django 3.2.19 on 2023-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_salesordershipment_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorderlineitem',
            name='outcome',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (20, 'Return'), (30, 'Repair'), (40, 'Replace'), (50, 'Refund'), (60, 'Reject')], default=10, help_text='Outcome for this line item', verbose_name='Outcome'),
        ),
    ]
