# Generated by Django 3.2.19 on 2023-06-30 06:09

from django.db import migrations, models
from InvenTree.status_codes import PurchaseOrderStatus


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0097_auto_20230529_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.PositiveIntegerField(choices=PurchaseOrderStatus.items(), default=10, help_text='Purchase order status'),
        ),
    ]
