# Generated by Django 3.2.22 on 2023-11-01 17:47

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_auto_20231024_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderextraline',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='returnorderextraline',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='returnorderlineitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='salesorderextraline',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),
        ),
    ]
