# Generated by Django 4.2.11 on 2024-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_auto_20231024_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Pending'), (15, 'In Progress'), (20, 'Shipped'), (30, 'Complete'), (40, 'Cancelled'), (50, 'Lost'), (60, 'Returned')], default=10, help_text='Purchase order status', verbose_name='Status'),
        ),
    ]
