# Generated by Django 3.2.5 on 2022-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0003_pluginsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginsetting',
            name='key',
            field=models.CharField(help_text='Settings key (must be unique - case insensitive)', max_length=50),
        ),
    ]
