# Generated by Django 3.2.18 on 2023-05-09 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20230509_0619'),
        ('plugin', '0005_notificationusersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Settings key (must be unique - case insensitive)', max_length=50)),
                ('value', models.CharField(blank=True, help_text='Settings value', max_length=200)),
                ('connection_key', models.CharField(help_text='connection key', max_length=255, verbose_name='Connection key')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='common.webconnection', verbose_name='Connection')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_settings', to='plugin.pluginconfig', verbose_name='Plugin')),
            ],
            options={
                'unique_together': {('connection', 'connection_key', 'plugin', 'key')},
            },
        ),
    ]
