# Generated by Django 3.2.19 on 2023-06-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0005_notificationusersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginconfig',
            name='metadata',
            field=models.JSONField(blank=True, help_text='JSON metadata field, for use by external plugins', null=True, verbose_name='Plugin Metadata'),
        ),
    ]
