# Generated by Django 3.2.21 on 2023-10-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0007_auto_20230805_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginconfig',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated'),
        ),
    ]
