# Generated by Django 3.2.5 on 2021-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderbasket',
            name='status',
            field=models.CharField(choices=[(1, 'Busy'), (0, 'Empty'), (2, 'Waiting for packing')], default=0, max_length=2),
        ),
    ]
