# Generated by Django 5.2.17 on 2026-09-09 06:48

import InvenTree.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("order", "0001_initial"),
        ("order", "0002_auto_20190604_2224"),
        ("order", "0003_auto_20190604_2226"),
        ("order", "0004_purchaseorder_status"),
        ("order", "0005_purchaseorderlineitem_part"),
        ("order", "0006_auto_20190605_2056"),
        ("order", "0007_auto_20190605_2138"),
        ("order", "0008_auto_20190605_2140"),
        ("order", "0009_auto_20190606_2133"),
        ("order", "0010_purchaseorderlineitem_notes"),
        ("order", "0011_auto_20190615_1928"),
        ("order", "0012_auto_20190617_1943"),
        ("order", "0013_auto_20191118_2323"),
        ("order", "0014_auto_20191118_2328"),
        ("order", "0015_auto_20200201_2346"),
        ("order", "0016_purchaseorderattachment"),
        ("order", "0017_auto_20200331_1000"),
        ("order", "0018_auto_20200406_0151"),
        ("order", "0019_purchaseorder_supplier_reference"),
        ("order", "0020_auto_20200420_0940"),
        ("order", "0021_auto_20200420_1010"),
        ("order", "0022_salesorderlineitem_part"),
        ("order", "0023_auto_20200420_2309"),
    ]

    initial = True

    dependencies = [
        ("company", "0005_auto_20190525_2356"),
        ("company", "0021_remove_supplierpart_manufacturer_name"),
        ("part", "0035_auto_20200406_0045"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Order reference", max_length=64, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Order description", max_length=250),
                ),
                ("creation_date", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Order notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier",
                        limit_choices_to={"is_supplier": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="company.company",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, help_text="Link to external page"),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "Pending"),
                            (20, "Placed"),
                            (30, "Complete"),
                            (40, "Cancelled"),
                            (50, "Lost"),
                            (60, "Returned"),
                        ],
                        default=10,
                        help_text="Order status",
                    ),
                ),
                ("complete_date", models.DateField(blank=True, null=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier_reference",
                    models.CharField(
                        blank=True,
                        help_text="Supplier order reference code",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Purchase Order",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        help_text="Select file to attach", upload_to="attachments"
                    ),
                ),
                ("comment", models.CharField(help_text="File comment", max_length=100)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="order.purchaseorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLineItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    InvenTree.fields.RoundingDecimalField(
                        decimal_places=5,
                        default=1,
                        help_text="Item quantity",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="Line item reference", max_length=100
                    ),
                ),
                (
                    "received",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        help_text="Number of items received",
                        max_digits=15,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Purchase Order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="order.purchaseorder",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier part",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_line_items",
                        to="company.supplierpart",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, help_text="Line item notes", max_length=500
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Purchase Order Line Item",
                "unique_together": {("order", "part")},
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Order reference", max_length=64, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Order description", max_length=250),
                ),
                (
                    "link",
                    models.URLField(blank=True, help_text="Link to external page"),
                ),
                ("creation_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "Pending"),
                            (20, "Placed"),
                            (30, "Complete"),
                            (40, "Cancelled"),
                            (50, "Lost"),
                            (60, "Returned"),
                        ],
                        default=10,
                        help_text="Order status",
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Order notes")),
                (
                    "customer_reference",
                    models.CharField(
                        blank=True,
                        help_text="Customer order reference code",
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer",
                        limit_choices_to={"is_customer": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Sales Order",
            },
        ),
        migrations.CreateModel(
            name="SalesOrderAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        help_text="Select file to attach", upload_to="attachments"
                    ),
                ),
                ("comment", models.CharField(help_text="File comment", max_length=100)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="order.salesorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLineItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    InvenTree.fields.RoundingDecimalField(
                        decimal_places=5,
                        default=1,
                        help_text="Item quantity",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="Line item reference", max_length=100
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, help_text="Line item notes", max_length=500
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Sales Order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="order.salesorder",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        help_text="Part",
                        limit_choices_to={"salable": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_order_line_items",
                        to="part.part",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Sales Order Line Item",
            },
        ),
    ]
