# Generated by Django 4.2.19 on 2025-03-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('order', '0106_purchaseorder_start_date_returnorder_start_date_and_more')]

    initial = True

    dependencies = [
        ('order', '0001_remaked_20250311'),
        ('part', '0001_remaked_20250311'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderlineitem',
            name='part',
            field=models.ForeignKey(help_text='Part', limit_choices_to={'salable': True, 'virtual': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_line_items', to='part.part', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='order',
            field=models.ForeignKey(help_text='Sales Order', on_delete=django.db.models.deletion.CASCADE, related_name='extra_lines', to='order.salesorder', verbose_name='Order'),
        ),
    ]
