# Generated by Django 4.2.23 on 2025-07-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("order", "0002_auto_20190604_2224"),
        ("order", "0003_auto_20190604_2226"),
        ("order", "0004_purchaseorder_status"),
    ]

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="URL",
            field=models.URLField(blank=True, help_text="Link to external page"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="description",
            field=models.CharField(
                blank=True, help_text="Order description", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Company",
                limit_choices_to={"is_supplier": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Orders",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Company",
                limit_choices_to={"is_supplier": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "Pending"),
                    (20, "Placed"),
                    (30, "Complete"),
                    (40, "Cancelled"),
                    (50, "Lost"),
                    (60, "Returned"),
                ],
                default=10,
                help_text="Order status",
            ),
        ),
    ]
