# Generated by Django 2.2 on 2019-06-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('order', '0002_auto_20190604_2224')]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(
                help_text='Company',
                limit_choices_to={'is_supplier': True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='purchase_orders',
                to='company.Company',
            ),
        )
    ]
