# Generated by Django 4.2.19 on 2025-03-10 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    replaces = [('order', '0108_alter_purchaseorder_link_and_more_squashed_0109_alter_purchaseorderextraline_link_and_more')]

    initial = True

    dependencies = [
        ('auth', '__first__'),
        ('common', '0001_remaked_20250310'),
        ('company', '0002_remaked_20250310'),
        ('stock', '0001_remaked_20250310'),
        ('users', '0001_remaked_20250310'),
        ('order', '0003_remaked_20250310'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.owner', verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='shipped by'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='item',
            field=models.ForeignKey(help_text='Select item to return from customer', on_delete=django.db.models.deletion.CASCADE, related_name='return_order_lines', to='stock.stockitem', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='order',
            field=models.ForeignKey(help_text='Return Order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.returnorder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='order',
            field=models.ForeignKey(help_text='Return Order', on_delete=django.db.models.deletion.CASCADE, related_name='extra_lines', to='order.returnorder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='customer',
            field=models.ForeignKey(help_text='Company from which items are being returned', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='company.company', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='project_code',
            field=models.ForeignKey(blank=True, help_text='Select project code for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.projectcode', verbose_name='Project Code'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.owner', verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='destination',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Destination for received items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='stock.stocklocation', verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='order',
            field=models.ForeignKey(help_text='Purchase Order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.purchaseorder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='part',
            field=models.ForeignKey(help_text='Supplier part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_line_items', to='company.supplierpart', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='purchaseorderextraline',
            name='order',
            field=models.ForeignKey(help_text='Purchase Order', on_delete=django.db.models.deletion.CASCADE, related_name='extra_lines', to='order.purchaseorder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='destination',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Destination for received items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='stock.stocklocation', verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project_code',
            field=models.ForeignKey(blank=True, help_text='Select project code for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.projectcode', verbose_name='Project Code'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='received by'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='User or group responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.owner', verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Company from which the items are being ordered', limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='company.company', verbose_name='Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='salesordershipment',
            unique_together={('order', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='returnorderlineitem',
            unique_together={('order', 'item')},
        ),
    ]
