# Generated by Django 2.2 on 2019-06-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190525_2356'),
        ('order', '0004_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Supplier part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='company.SupplierPart'),
        ),
    ]
