# Generated by Django 4.2.23 on 2025-07-13 11:35

import InvenTree.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("order", "0007_auto_20190605_2138"),
        ("order", "0008_auto_20190605_2140"),
        ("order", "0009_auto_20190606_2133"),
        ("order", "0010_purchaseorderlineitem_notes"),
        ("order", "0011_auto_20190615_1928"),
        ("order", "0012_auto_20190617_1943"),
        ("order", "0013_auto_20191118_2323"),
        ("order", "0014_auto_20191118_2328"),
        ("order", "0015_auto_20200201_2346"),
        ("order", "0016_purchaseorderattachment"),
        ("order", "0017_auto_20200331_1000"),
        ("order", "0018_auto_20200406_0151"),
        ("order", "0019_purchaseorder_supplier_reference"),
    ]

    dependencies = [
        ("order", "0006_auto_20190605_2056"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="part",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier part",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_line_items",
                to="company.supplierpart",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="part",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier part",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_line_items",
                to="company.supplierpart",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="description",
            field=models.CharField(help_text="Order description", max_length=250),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="notes",
            field=models.CharField(
                blank=True, help_text="Line item notes", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="creation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=5,
                default=1,
                help_text="Item quantity",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="received",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                help_text="Number of items received",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True, help_text="Order notes"),
        ),
        migrations.CreateModel(
            name="PurchaseOrderAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        help_text="Select file to attach", upload_to="attachments"
                    ),
                ),
                ("comment", models.CharField(help_text="File comment", max_length=100)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="order.purchaseorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="quantity",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=5,
                default=1,
                help_text="Item quantity",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="URL",
            new_name="link",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_reference",
            field=models.CharField(
                blank=True, help_text="Supplier order reference", max_length=64
            ),
        ),
    ]
