# Generated by Django 2.2.2 on 2019-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190606_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='notes',
            field=models.CharField(blank=True, help_text='Line item notes', max_length=500),
        ),
    ]
