# Generated by Django 2.2.5 on 2019-11-18 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20190617_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Item quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
