# Generated by Django 2.2.5 on 2019-11-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20191118_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='received',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Number of items received', max_digits=15),
        ),
    ]
