# Generated by Django 2.2.10 on 2020-04-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20200331_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='URL',
            new_name='link',
        ),
    ]
