# Generated by Django 2.2.10 on 2020-04-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200406_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_reference',
            field=models.CharField(blank=True, help_text='Supplier order reference', max_length=64),
        ),
    ]
