# Generated by Django 3.0.5 on 2020-04-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_auto_20200422_0209'),
        ('order', '0024_salesorderallocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesorderallocation',
            unique_together={('line', 'item')},
        ),
    ]
