# Generated by Django 3.0.5 on 2020-04-22 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_auto_20200422_0209'),
        ('order', '0026_auto_20200422_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderallocation',
            name='item',
            field=models.ForeignKey(limit_choices_to={'part__salable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_allocations', to='stock.StockItem'),
        ),
    ]
