# Generated by Django 3.0.5 on 2020-04-23 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0028_auto_20200423_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='complete_date',
            new_name='shipment_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
