# Generated by Django 4.2.23 on 2025-07-13 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("order", "0032_auto_20200427_0044"),
        ("order", "0033_auto_20200512_1033"),
        ("order", "0034_auto_20200512_1054"),
        ("order", "0035_auto_20200513_0016"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("part", "0035_auto_20200406_0045"),
        ("order", "0031_auto_20200426_0612"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salesorderlineitem",
            unique_together={("order", "part")},
        ),
        migrations.AddField(
            model_name="purchaseorderattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorderattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderattachment",
            name="upload_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorderattachment",
            name="upload_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderattachment",
            name="comment",
            field=models.CharField(
                blank=True, help_text="File comment", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="comment",
            field=models.CharField(
                blank=True, help_text="File comment", max_length=100
            ),
        ),
    ]
