# Generated by Django 3.0.5 on 2020-05-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20200512_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderattachment',
            name='comment',
            field=models.CharField(blank=True, help_text='File comment', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorderattachment',
            name='comment',
            field=models.CharField(blank=True, help_text='File comment', max_length=100),
        ),
    ]
