# Generated by Django 4.2.23 on 2025-07-13 11:38

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    replaces = [
        ("order", "0039_auto_20201112_2203"),
        ("order", "0040_salesorder_target_date"),
        ("order", "0041_auto_20210114_1728"),
        ("order", "0042_auto_20210310_1619"),
        ("order", "0043_auto_20210330_0013"),
    ]

    dependencies = [
        ("order", "0038_auto_20201112_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="purchase_price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=4,
                default_currency="USD",
                help_text="Unit purchase price",
                max_digits=19,
                null=True,
                verbose_name="Purchase Price",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for order completion. Order will be overdue after this date.",
                null=True,
                verbose_name="Target completion date",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Expected date for order delivery. Order will be overdue after this date.",
                null=True,
                verbose_name="Target Delivery Date",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="complete_date",
            field=models.DateField(
                blank=True,
                help_text="Date order was completed",
                null=True,
                verbose_name="Completion Date",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateField(
                blank=True,
                help_text="Date order was issued",
                null=True,
                verbose_name="Issue Date",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="User or group responsible for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="User or group responsible for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesorderlineitem",
            unique_together=set(),
        ),
    ]
