# Generated by Django 3.0.7 on 2021-03-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20210310_1619'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesorderlineitem',
            unique_together=set(),
        ),
    ]
