# Generated by Django 3.2.5 on 2021-10-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_alter_purchaseorderlineitem_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='reference_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='reference_int',
            field=models.IntegerField(default=0),
        ),
    ]
