# Generated by Django 4.2.23 on 2025-07-13 12:36

import InvenTree.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("order", "0053_auto_20211128_0151"),
        ("order", "0053_salesordershipment"),
        ("order", "0054_auto_20211201_2139"),
        ("order", "0054_salesorderallocation_shipment"),
    ]

    dependencies = [
        ("order", "0052_auto_20211014_0631"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderattachment",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external URL",
                max_length=2000,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="salesorderattachment",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external URL",
                max_length=2000,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderattachment",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Select file to attach",
                null=True,
                upload_to="attachments",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Select file to attach",
                null=True,
                upload_to="attachments",
                verbose_name="Attachment",
            ),
        ),
        migrations.CreateModel(
            name="SalesOrderShipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of shipment",
                        null=True,
                        verbose_name="Shipment Date",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default="1",
                        help_text="Shipment reference",
                        max_length=100,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Shipment notes", verbose_name="Notes"
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who checked this shipment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Checked By",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Sales Order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="order.salesorder",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order Shipment",
            },
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="reference_int",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="reference_int",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales order shipment reference",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.salesordershipment",
                verbose_name="Shipment",
            ),
        ),
    ]
