# Generated by Django 3.2.5 on 2021-10-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('order', '0053_salesordershipment')]

    operations = [
        migrations.AddField(
            model_name='salesorderallocation',
            name='shipment',
            field=models.ForeignKey(
                blank=True,
                help_text='Sales order shipment reference',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='order.salesordershipment',
                verbose_name='Shipment',
            ),
        )
    ]
