# Generated by Django 3.2.5 on 2021-10-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_salesordershipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderallocation',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Sales order shipment reference', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.salesordershipment', verbose_name='Shipment'),
        ),
    ]
