# Generated by Django 3.2.5 on 2021-10-25 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_auto_20211025_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderallocation',
            name='shipment',
            field=models.ForeignKey(help_text='Sales order shipment reference', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='order.salesordershipment', verbose_name='Shipment'),
        ),
    ]
