# Generated by Django 3.2.5 on 2021-12-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20211201_2139'),
        ('order', '0060_auto_20211129_1339'),
    ]

    operations = [
    ]
