# Generated by Django 3.2.10 on 2022-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_merge_0054_auto_20211201_2139_0060_auto_20211129_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target shipping date for this line item', null=True, verbose_name='Target Date'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target shipping date for this line item', null=True, verbose_name='Target Date'),
        ),
    ]
