# Generated by Django 4.2.23 on 2025-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("order", "0062_auto_20220228_0321"),
        ("order", "0063_alter_purchaseorderlineitem_unique_together"),
    ]

    dependencies = [
        ("order", "0061_merge_0054_auto_20211201_2139_0060_auto_20211129_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target shipping date for this line item",
                null=True,
                verbose_name="Target Date",
            ),
        ),
        migrations.AddField(
            model_name="salesorderlineitem",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target shipping date for this line item",
                null=True,
                verbose_name="Target Date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderlineitem",
            unique_together=set(),
        ),
    ]
