# Generated by Django 4.2.23 on 2025-07-13 11:45

import InvenTree.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("order", "0066_alter_purchaseorder_supplier"),
        ("order", "0067_auto_20220516_1120"),
        ("order", "0068_alter_salesorderallocation_unique_together"),
        ("order", "0069_auto_20220524_0508"),
        ("order", "0070_auto_20220620_0728"),
    ]

    dependencies = [
        ("order", "0065_alter_purchaseorderlineitem_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Company from which the items are being ordered",
                limit_choices_to={"is_supplier": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="company.company",
                verbose_name="Supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesorderallocation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="salesordershipment",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Reference number for associated invoice",
                max_length=100,
                verbose_name="Invoice Number",
            ),
        ),
        migrations.AddField(
            model_name="salesordershipment",
            name="link",
            field=models.URLField(
                blank=True, help_text="Link to external page", verbose_name="Link"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Order notes",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Order notes",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="salesordershipment",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Shipment notes",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
    ]
