# Generated by Django 3.2.13 on 2022-05-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_auto_20220516_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesorderallocation',
            unique_together=set(),
        ),
    ]
