# Generated by Django 3.2.14 on 2022-07-07 11:55

from django.db import migrations, models
import order.validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20220628_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='reference',
            field=models.CharField(default=order.validators.generate_next_sales_order_reference, help_text='Order reference', max_length=64, unique=True, validators=[order.validators.validate_sales_order_reference], verbose_name='Reference'),
        ),
    ]
