# Generated by Django 4.2.23 on 2025-07-13 11:46

import InvenTree.fields
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    replaces = [
        ("order", "0075_auto_20221110_0108"),
        ("order", "0076_auto_20221111_0153"),
        ("order", "0077_auto_20230129_0154"),
        ("order", "0078_auto_20230304_0721"),
    ]

    dependencies = [
        ("order", "0074_auto_20220709_0108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="salesordershipment",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderextraline",
            name="price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Unit price",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="purchase_price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Unit purchase price",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Purchase Price",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderextraline",
            name="price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Unit price",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="sale_price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Unit sale price",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Sale Price",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderextraline",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for this line item (leave blank to use the target date from the order)",
                null=True,
                verbose_name="Target Date",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for this line item (leave blank to use the target date from the order)",
                null=True,
                verbose_name="Target Date",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderextraline",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for this line item (leave blank to use the target date from the order)",
                null=True,
                verbose_name="Target Date",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for this line item (leave blank to use the target date from the order)",
                null=True,
                verbose_name="Target Date",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="total_price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Total price for this order",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Total Price",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="total_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="total_price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=6,
                default_currency="",
                help_text="Total price for this order",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Total Price",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="total_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3
            ),
        ),
    ]
