# Generated by Django 4.2.23 on 2025-07-13 11:47

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("order", "0086_auto_20230323_1108"),
        ("order", "0087_alter_salesorder_status"),
        ("order", "0088_auto_20230403_1402"),
        ("order", "0089_auto_20230404_0030"),
        ("order", "0090_auto_20230412_1752"),
        ("order", "0091_auto_20230419_0037"),
    ]

    dependencies = [
        ("order", "0085_auto_20230322_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnorderextraline",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AddField(
            model_name="returnorderlineitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "Pending"),
                    (15, "In Progress"),
                    (20, "Shipped"),
                    (25, "On Hold"),
                    (30, "Complete"),
                    (40, "Cancelled"),
                    (50, "Lost"),
                    (60, "Returned"),
                ],
                default=10,
                help_text="Sales order status",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderextraline",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="returnorderextraline",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="salesorderextraline",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="salesorderlineitem",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Order description (optional)",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Order description (optional)",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Order description (optional)",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="salesordershipment",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
    ]
