# Generated by Django 4.2.23 on 2025-07-13 11:48

import InvenTree.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("order", "0093_auto_20230426_0248"),
        ("order", "0094_auto_20230514_2331"),
        ("order", "0095_salesordershipment_delivery_date"),
        ("order", "0096_alter_returnorderlineitem_outcome"),
    ]

    dependencies = [
        ("order", "0092_auto_20230419_0250"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="order_currency",
            field=models.CharField(
                blank=True,
                help_text="Currency for this order (leave blank to use company default)",
                max_length=3,
                null=True,
                validators=[InvenTree.validators.validate_currency_code],
                verbose_name="Order Currency",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="order_currency",
            field=models.CharField(
                blank=True,
                help_text="Currency for this order (leave blank to use company default)",
                max_length=3,
                null=True,
                validators=[InvenTree.validators.validate_currency_code],
                verbose_name="Order Currency",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="order_currency",
            field=models.CharField(
                blank=True,
                help_text="Currency for this order (leave blank to use company default)",
                max_length=3,
                null=True,
                validators=[InvenTree.validators.validate_currency_code],
                verbose_name="Order Currency",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderextraline",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Line item description (optional)",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="returnorderextraline",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Line item description (optional)",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="salesorderextraline",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Line item description (optional)",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="salesordershipment",
            name="delivery_date",
            field=models.DateField(
                blank=True,
                help_text="Date of delivery of shipment",
                null=True,
                verbose_name="Delivery Date",
            ),
        ),
        migrations.AlterField(
            model_name="returnorderlineitem",
            name="outcome",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "Pending"),
                    (20, "Return"),
                    (30, "Repair"),
                    (40, "Replace"),
                    (50, "Refund"),
                    (60, "Reject"),
                ],
                default=10,
                help_text="Outcome for this line item",
                verbose_name="Outcome",
            ),
        ),
    ]
