# Generated by Django 4.2.23 on 2025-07-13 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    replaces = [
        ("order", "0102_purchaseorder_destination_and_more"),
        ("order", "0103_alter_salesorderallocation_shipment"),
        ("order", "0104_alter_returnorderlineitem_quantity"),
    ]

    dependencies = [
        ("order", "0101_purchaseorder_status_custom_key_and_more"),
        ("stock", "0113_stockitem_status_custom_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="destination",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Destination for received items",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="stock.stocklocation",
                verbose_name="Destination",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="destination",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Destination for received items",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_lines",
                to="stock.stocklocation",
                verbose_name="Destination",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales order shipment reference",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="order.salesordershipment",
                verbose_name="Shipment",
            ),
        ),
        migrations.AlterField(
            model_name="returnorderlineitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=5,
                default=1,
                help_text="Quantity to return",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
    ]
