# Generated by Django 4.2.16 on 2024-11-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0102_purchaseorder_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderallocation',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Sales order shipment reference', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='order.salesordershipment', verbose_name='Shipment'),
        ),
    ]
