# Generated by Django 4.2.18 on 2025-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0105_auto_20241128_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='start_date',
            field=models.DateField(blank=True, help_text='Scheduled start date for this order', null=True, verbose_name='Start date'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='start_date',
            field=models.DateField(blank=True, help_text='Scheduled start date for this order', null=True, verbose_name='Start date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='start_date',
            field=models.DateField(blank=True, help_text='Scheduled start date for this order', null=True, verbose_name='Start date'),
        ),
    ]
