# Generated by Django 4.2.23 on 2025-07-13 11:49

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("order", "0106_purchaseorder_start_date_returnorder_start_date_and_more"),
        ("order", "0107_auto_20250221_1241"),
        (
            "order",
            "0108_alter_purchaseorder_link_and_more_squashed_0109_alter_purchaseorderextraline_link_and_more",
        ),
        ("order", "0109_salesorder_issue_date"),
    ]

    dependencies = [
        ("order", "0105_auto_20241128_0431"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Scheduled start date for this order",
                null=True,
                verbose_name="Start date",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Scheduled start date for this order",
                null=True,
                verbose_name="Start date",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Scheduled start date for this order",
                null=True,
                verbose_name="Start date",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnorderlineitem",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderextraline",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderextraline",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnorderextraline",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesordershipment",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="returnorderlineitem",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="salesordershipment",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderextraline",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="returnorderextraline",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderextraline",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external page",
                max_length=2000,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="issue_date",
            field=models.DateField(
                blank=True,
                help_text="Date order was issued",
                null=True,
                verbose_name="Issue Date",
            ),
        ),
    ]
