# Generated by Django 4.2.19 on 2025-02-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0106_purchaseorder_start_date_returnorder_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="issue_date",
            field=models.DateField(
                blank=True,
                help_text="Date order was issued",
                null=True,
                verbose_name="Issue Date",
            ),
        ),
    ]
