# Generated by Django 4.2.20 on 2025-04-10 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("build", "0057_build_external"),
        ("order", "0109_salesorder_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="build_order",
            field=models.ForeignKey(
                blank=True,
                help_text="External Build Order to be fulfilled by this line item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_line_items",
                to="build.build",
                verbose_name="Build Order",
            ),
        ),
    ]
