# Generated by Django 4.2.20 on 2025-03-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("build", "0056_alter_build_link"),
        (
            "order",
            "0108_alter_purchaseorder_link_and_more_squashed_0109_alter_purchaseorderextraline_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="build_order",
            field=models.OneToOneField(
                blank=True,
                help_text="External Build Order for this line item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_line",
                to="build.build",
                verbose_name="Build Order",
            ),
        ),
    ]
