# Generated by Django 4.2.23 on 2025-10-04 21:14

import InvenTree.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
        ('order', '0111_purchaseorderlineitem_build_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='subtotal',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Subtotal for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='tax_amount',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax amount for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='tax_configuration',
            field=models.ForeignKey(blank=True, help_text='Original tax configuration (may have changed since order)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.taxconfiguration', verbose_name='Tax Configuration'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='tax_inclusive',
            field=models.BooleanField(default=False, help_text='Whether prices in this order include tax', verbose_name='Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate applied to this order', max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='total_with_tax',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Total with tax for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Total with Tax'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='total_with_tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='is_tax_inclusive',
            field=models.BooleanField(blank=True, help_text='Whether prices for this item include tax', null=True, verbose_name='Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='price_with_tax',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Price with tax for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Price with Tax'),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='price_with_tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='subtotal',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Subtotal for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='tax_amount',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax amount for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='tax_per_item',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax per item for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax per Item'),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='tax_per_item_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderextraline',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate for this line item. Leave blank to use order default.', max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='is_tax_inclusive',
            field=models.BooleanField(blank=True, help_text='Whether prices for this item include tax', null=True, verbose_name='Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='price_with_tax',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Price with tax for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Price with Tax'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='price_with_tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='subtotal',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Subtotal for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='tax_amount',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax amount for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='tax_per_item',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax per item for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax per Item'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='tax_per_item_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate for this line item. Leave blank to use order default.', max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Subtotal for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_amount',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax amount for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_configuration',
            field=models.ForeignKey(blank=True, help_text='Original tax configuration (may have changed since order)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.taxconfiguration', verbose_name='Tax Configuration'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_inclusive',
            field=models.BooleanField(default=False, help_text='Whether prices in this order include tax', verbose_name='Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate applied to this order', max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_with_tax',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Total with tax for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Total with Tax'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total_with_tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='is_tax_inclusive',
            field=models.BooleanField(blank=True, help_text='Whether prices for this item include tax', null=True, verbose_name='Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='price_with_tax',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Price with tax for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Price with Tax'),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='price_with_tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='subtotal',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Subtotal for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='tax_amount',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax amount for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='tax_per_item',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax per item for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax per Item'),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='tax_per_item_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderextraline',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate for this line item. Leave blank to use order default.', max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='is_tax_inclusive',
            field=models.BooleanField(blank=True, help_text='Whether prices for this item include tax', null=True, verbose_name='Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='price_with_tax',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Price with tax for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Price with Tax'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='price_with_tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='subtotal',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Subtotal for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='tax_amount',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax amount for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='tax_per_item',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Tax per item for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Tax per Item'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='tax_per_item_currency',
            field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate for this line item. Leave blank to use order default.', max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_price',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Total price for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='total_price',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Total price for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='returnorderlineitem',
            name='price',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Cost associated with return or repair for this line item', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_price',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=2, default_currency='', help_text='Total price for this order', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Total Price'),
        ),
    ]
