# Generated by Django 4.2.23 on 2025-09-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0142_remove_part_last_stocktake_remove_partstocktake_note_and_more"),
        ("order", "0111_purchaseorderlineitem_build_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="part",
            field=models.ForeignKey(
                help_text="Part",
                limit_choices_to={"salable": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_order_line_items",
                to="part.part",
                verbose_name="Part",
            ),
        ),
    ]
