# Generated by Django 4.2.25 on 2025-10-24 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_emailthread_emailmessage"),
        ("order", "0113_salesordershipment_shipment_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderextraline",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="returnorderextraline",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="returnorderlineitem",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="salesorderextraline",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="salesorderlineitem",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
    ]
