# Generated by Django 5.2.11 on 2026-02-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0114_purchaseorderextraline_project_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp of last update",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp of last update",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp of last update",
                verbose_name="Updated At",
            ),
        ),
    ]
