# Generated by Django 5.2.9 on 2026-01-09 20:57

import InvenTree.fields
import InvenTree.models
import django.core.validators
import django.db.models.deletion
import generic.states.fields
import generic.states.validators
import order.status_codes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_auto_20251203_1244"),
        ("order", "0115_transferorder"),
        ("part", "0146_auto_20251203_1241"),
        ("stock", "0116_alter_stockitem_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferorder",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination for transferred items",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_transfers",
                to="stock.stocklocation",
                verbose_name="Destination Location",
            ),
        ),
        migrations.AlterField(
            model_name="transferorder",
            name="status",
            field=generic.states.fields.InvenTreeCustomStatusModelField(
                choices=[
                    (10, "Pending"),
                    (20, "Issued"),
                    (25, "On Hold"),
                    (30, "Complete"),
                    (40, "Cancelled"),
                ],
                default=10,
                help_text="Transfer order status",
                validators=[
                    generic.states.validators.CustomStatusCodeValidator(
                        status_class=order.status_codes.TransferOrderStatus
                    )
                ],
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="transferorder",
            name="take_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Source for transferred items",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sourcing_transfers",
                to="stock.stocklocation",
                verbose_name="Source Location",
            ),
        ),
        migrations.CreateModel(
            name="TransferOrderLineItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
                (
                    "quantity",
                    InvenTree.fields.RoundingDecimalField(
                        decimal_places=5,
                        default=1,
                        help_text="Item quantity",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Line item reference",
                        max_length=100,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Line item notes",
                        max_length=500,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "link",
                    InvenTree.fields.InvenTreeURLField(
                        blank=True,
                        help_text="Link to external page",
                        max_length=2000,
                        verbose_name="Link",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="Target date for this line item (leave blank to use the target date from the order)",
                        null=True,
                        verbose_name="Target Date",
                    ),
                ),
                (
                    "transfered",
                    InvenTree.fields.RoundingDecimalField(
                        decimal_places=5,
                        default=0,
                        help_text="Transfered quantity",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Transfered",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Transfer Order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="order.transferorder",
                        verbose_name="Order",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        help_text="Part",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_order_line_items",
                        to="part.part",
                        verbose_name="Part",
                    ),
                ),
                (
                    "project_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select project code for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.projectcode",
                        verbose_name="Project Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Order Line Item",
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TransferOrderAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    InvenTree.fields.RoundingDecimalField(
                        decimal_places=5,
                        default=1,
                        help_text="Enter stock allocation quantity",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Select stock item to allocate",
                        limit_choices_to={
                            "belongs_to": None,
                            "part__virtual": False,
                            "sales_order": None,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_order_allocations",
                        to="stock.stockitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="order.transferorderlineitem",
                        verbose_name="Line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Order Allocation",
            },
        ),
    ]
