# Generated by Django 5.2.9 on 2026-02-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0114_purchaseorderextraline_project_code_and_more'),
        ('tenant', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this order belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_orders', to='tenant.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this order belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_orders', to='tenant.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this order belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_orders', to='tenant.tenant', verbose_name='Tenant'),
        ),
    ]
