# Generated by Django 5.2.9 on 2026-01-09 21:49

import InvenTree.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0116_alter_transferorder_destination_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferorderlineitem",
            name="transfered",
        ),
        migrations.AddField(
            model_name="transferorderlineitem",
            name="transferred",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=5,
                default=0,
                help_text="transferred quantity",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="transferred",
            ),
        ),
    ]
