# Generated by Django 5.2.11 on 2026-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0116_transferorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferorder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last update",
                null=True,
                verbose_name="Updated At",
            ),
        ),
    ]
