# Generated by Django 5.2.13 on 2026-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('order', '0118_transferorder')]

    operations = [
        migrations.AddField(
            model_name='transferorderlineitem',
            name='line_int',
            field=models.IntegerField(default=0),
        )
    ]
