# Generated by Django 5.2.14 on 2026-05-31 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0080_alter_address_company"),
        ("order", "0119_transferorderlineitem_line_int"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Address for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="returnorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Address for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Address for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="transferorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Address for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.address",
                verbose_name="Address",
            ),
        ),
    ]
