# Generated by Django 5.2.14 on 2026-05-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0120_purchaseorder_tags_returnorder_tags_salesorder_tags_and_more"),
        ("common", "0050_remove_notesimage_model_id_and_more")
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="returnorder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="salesordershipment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="transferorder",
            name="notes",
        ),
    ]
