# Generated by Django - merge migration for order app
# Merges the two 0121 migration branches:
# - 0121_add_line_item_discount (upstream: adds discount fields to line items)
# - 0121_merge_20260604_1637 (our branch: merges repair order migrations)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0121_add_line_item_discount'),
        ('order', '0121_merge_20260604_1637'),
    ]

    operations = [
    ]
