# Generated by Django 2.2.5 on 2019-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190902_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvenTreeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Settings key', max_length=50, unique=True)),
                ('value', models.CharField(blank=True, help_text='Settings value', max_length=200)),
            ],
        ),
    ]
