# Generated by Django 3.0.7 on 2020-11-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_remove_supplierpricebreak_currency'),
        ('part', '0057_remove_partsellpricebreak_currency'),
        ('common', '0008_remove_inventreesetting_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
