# Generated by Django 4.2.15 on 2024-10-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0031_auto_20241026_0024"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ColorTheme",
        ),
    ]
