# Generated by Django 4.2.16 on 2024-11-24 05:41

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20241026_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventreecustomuserstatemodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inventreecustomuserstatemodel',
            name='key',
            field=models.IntegerField(help_text='Numerical value that will be saved in the models database', verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='inventreecustomuserstatemodel',
            name='name',
            field=models.CharField(help_text='Name of the state', max_length=250, validators=[common.validators.validate_uppercase, common.validators.validate_variable_string], verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='inventreecustomuserstatemodel',
            unique_together={('reference_status', 'key'), ('reference_status', 'name')},
        ),
    ]
