# Generated by Django 4.2.17 on 2024-12-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_selectionlist_selectionlistentry_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ColorTheme",
        ),
    ]
