# Generated by Django 4.2.19 on 2025-02-21 15:13

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0034_alter_inventreecustomuserstatemodel_unique_together_and_more"),
    ]

    operations = [migrations.AlterField(
            model_name='attachment',
            name='link',
            field=models.TextField(
                null=True, blank=True
            )  # Temporary change to force new ALTER COLUMN operation in the next migration
        ),
    ]
