# Generated by Django 4.2.20 on 2025-04-07 20:53

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [('common', '0037_dataoutput')]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='model_type',
            field=models.CharField(
                help_text='Target model type for image',
                max_length=100,
                validators=[common.validators.validate_attachment_model_type],
                verbose_name='Model type',
            ),
        )
    ]
