# Generated by Django 4.2.20 on 2025-05-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_emailthread_emailmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailthread",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="Unique key for this thread (used to identify the thread)",
                max_length=250,
                null=True,
                verbose_name="Key",
            ),
        ),
    ]
