# Generated by Django 4.2.22 on 2025-06-27 14:33

import common.validators
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_emailthread_emailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(help_text='Target model type for image', max_length=100, validators=[common.validators.validate_upload_image_model_type], verbose_name='Model type')),
                ('model_id', models.PositiveIntegerField()),
                ('primary', models.BooleanField(default=False)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='upload_images', variations={'preview': (256, 256), 'thumbnail': (128, 128)}, verbose_name='Image')),
            ],
        ),
    ]
