# Generated by Django 4.2.25 on 2025-10-28 11:11

import InvenTree.models
import InvenTree.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_emailthread_emailmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Parameter Name",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        blank=True,
                        help_text="Physical units for this parameter",
                        max_length=25,
                        validators=[InvenTree.validators.validate_physical_units],
                        verbose_name="Units",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Parameter description",
                        max_length=250,
                        verbose_name="Description",
                    ),
                ),
                (
                    "checkbox",
                    models.BooleanField(
                        default=False,
                        help_text="Is this parameter a checkbox?",
                        verbose_name="Checkbox",
                    ),
                ),
                (
                    "choices",
                    models.CharField(
                        blank=True,
                        help_text="Valid choices for this parameter (comma-separated)",
                        max_length=5000,
                        verbose_name="Choices",
                    ),
                ),
                (
                    "selectionlist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selection list for this parameter",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="common.selectionlist",
                        verbose_name="Selection List",
                    ),
                ),
            ],
            bases=(InvenTree.models.PluginValidationMixin, models.Model),
        ),
    ]
