# Generated by Django 4.2.20 on 2025-05-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_emailthread_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very High'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Very Low')], default=1, verbose_name='Prioriy'),
            preserve_default=False,
        ),
    ]
