# Generated by Django 4.2.20 on 2025-05-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_alter_emailthread_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmessage",
            old_name="recipient",
            new_name="to",
        ),
    ]
