# Generated by Django 4.2.25 on 2025-10-28 11:12

import structlog

from django.db import migrations

logger = structlog.get_logger('inventree')


def convert_to_numeric_value(value: str, units: str):
    """Convert a value (with units) to a numeric value.

    Defaults to zero if the value cannot be converted.
    """

    import InvenTree.conversion

    # Default value is null
    result = None

    if units:
        try:
            result = InvenTree.conversion.convert_physical_value(value, units)
            result = float(result.magnitude)
        except Exception:
            pass
    else:
        try:
            result = float(value)
        except Exception:
            pass

    return result


def update_global_setting(apps, schema_editor):
    """Update global setting key from PART_PARAMETER_ENFORCE_UNITS to PARAMETER_ENFORCE_UNITS."""
    GlobalSetting = apps.get_model("common", "InvenTreeSetting")

    OLD_KEY = 'PART_PARAMETER_ENFORCE_UNITS'
    NEW_KEY = 'PARAMETER_ENFORCE_UNITS'

    try:
        setting = GlobalSetting.objects.get(key=OLD_KEY)
        
        if setting is not None:
            # Remove any existing new key
            GlobalSetting.objects.filter(key=NEW_KEY).delete()
            setting.key = NEW_KEY
            setting.save()
            logger.info(f"Updated global setting key from {OLD_KEY} to {NEW_KEY}.")
    except GlobalSetting.DoesNotExist:
        logger.info(f"Global setting {OLD_KEY} does not exist; no update needed.")


def remove_existing_parameters(apps, schema_editor):
    """Remove any existing Parameter or ParameterTemplate objects from the database."""

    Parameter = apps.get_model("common", "Parameter")
    ParameterTemplate = apps.get_model("common", "ParameterTemplate")

    n_params = Parameter.objects.count()
    n_templates = ParameterTemplate.objects.count()

    Parameter.objects.all().delete()
    ParameterTemplate.objects.all().delete()

    if n_params > 0:
        logger.info(f"Removed {n_params} existing Parameter instances.")

    if n_templates > 0:
        logger.info(f"Removed {n_templates} existing ParameterTemplate instances.")

    assert Parameter.objects.count() == 0
    assert ParameterTemplate.objects.count() == 0


def copy_part_parameters(apps, schema_editor):
    """Forward migration: copy from PartParameterTemplate to ParameterTemplate."""

    ContentType = apps.get_model("contenttypes", "ContentType")
    PartParameterTemplate = apps.get_model("part", "PartParameterTemplate")
    ParameterTemplate = apps.get_model("common", "ParameterTemplate")
    PartParameter = apps.get_model("part", "PartParameter")
    Parameter = apps.get_model("common", "Parameter")

    # First, create a ParameterTemplate instance for each PartParameterTemplate
    templates = []

    for template in PartParameterTemplate.objects.all():
        templates.append(ParameterTemplate(
            name=template.name,
            description=template.description,
            units=template.units or '',
            checkbox=template.checkbox,
            choices=template.choices,
            selectionlist=template.selectionlist,
            model_type=None
        ))
    
    if len(templates) > 0:
        ParameterTemplate.objects.bulk_create(templates)
        logger.info(f"\nMigrated {len(templates)} PartParameterTemplate instances.")

    assert ParameterTemplate.objects.all().count() == len(templates)

    # Next, copy PartParameter instances to Parameter instances
    parameters = []

    content_type, _created = ContentType.objects.get_or_create(app_label='part', model='part')

    for parameter in PartParameter.objects.all():
        # Find the corresponding ParameterTemplate
        template = ParameterTemplate.objects.get(name=parameter.template.name)

        parameters.append(Parameter(
            template=template,
            model_type=content_type,
            model_id=parameter.part.id,
            data=parameter.data,
            data_numeric=parameter.data_numeric,
            note=parameter.note,
            metadata=parameter.metadata,
            updated=parameter.updated,
            updated_by=parameter.updated_by
        ))

    if len(parameters) > 0:
        Parameter.objects.bulk_create(parameters)
        logger.info(f"\nMigrated {len(parameters)} PartParameter instances.")

    assert Parameter.objects.filter(model_type=content_type).count() == len(parameters)


def copy_manufacturer_part_parameters(apps, schema_editor):
    """Copy ManufacturerPartParameter to Parameter."""

    ManufacturerPartParameter = apps.get_model("company", "ManufacturerPartParameter")
    Parameter = apps.get_model("common", "Parameter")
    ParameterTemplate = apps.get_model("common", "ParameterTemplate")
    ContentType = apps.get_model("contenttypes", "ContentType")
    parameters = []

    content_type, _created = ContentType.objects.get_or_create(app_label='company', model='manufacturerpart')

    for parameter in ManufacturerPartParameter.objects.all():
        # Find the corresponding ParameterTemplate
        template = ParameterTemplate.objects.filter(name=parameter.name).first()

        if not template:
            # A matching template does not exist - let's create one
            template = ParameterTemplate.objects.create(
                name=parameter.name,
                description='',
                units=parameter.units or '',
                model_type=None,
                checkbox=False
            )

        parameters.append(Parameter(
            template=template,
            model_type=content_type,
            model_id=parameter.manufacturer_part.id,
            data=parameter.value,
            data_numeric=convert_to_numeric_value(parameter.value, parameter.units),
        ))

    if len(parameters) > 0:
        Parameter.objects.bulk_create(parameters)
        logger.info(f"\nMigrated {len(parameters)} ManufacturerPartParameter instances.")

    assert Parameter.objects.filter(model_type=content_type).count() == len(parameters)


def update_category_parameters(apps, schema_editor):
    """Migration for PartCategoryParameterTemplate.
    
    Copies the contents of the 'parameter_template' field to the new 'template' field
    """

    PartCategoryParameterTemplate = apps.get_model("part", "partcategoryparametertemplate")
    ParameterTemplate = apps.get_model("common", "parametertemplate")

    to_update = []

    for item in PartCategoryParameterTemplate.objects.all():
        # Find a matching template
        item.template = ParameterTemplate.objects.get(
            name=item.parameter_template.name
        )

        to_update.append(item)

    if len(to_update) > 0:
        PartCategoryParameterTemplate.objects.bulk_update(to_update, ['template'])
        logger.info(f"Updated {len(to_update)} PartCategoryParameterTemplate instances.")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__latest__'),
        ("part", "0144_partcategoryparametertemplate_template"),
        ("company", "0034_manufacturerpart"),
        ("common", "0040_parametertemplate_parameter"),
    ]

    operations = [
        migrations.RunPython(
            update_global_setting,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            remove_existing_parameters,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            copy_part_parameters,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            copy_manufacturer_part_parameters,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            update_category_parameters,
            reverse_code=migrations.RunPython.noop
        )
    ]
