# Generated by Django 4.2.25 on 2025-10-28 11:12

from django.db import migrations


def copy_part_parameters(apps, schema_editor):
    """Forward migration: copy from PartParameterTemplate to ParameterTemplate."""
    PartParameterTemplate = apps.get_model("part", "PartParameterTemplate")
    ParameterTemplate = apps.get_model("common", "ParameterTemplate")

    PartParameter = apps.get_model("part", "PartParameter")
    Parameter = apps.get_model("common", "Parameter")

    # First, create a ParameterTemplate instance for each PartParameterTemplate
    templates = []

    for template in PartParameterTemplate.objects.all():
        templates.append(ParameterTemplate(
            name=template.name,
            description=template.description,
            units=template.units,
            checkbox=template.checkbox,
            choices=template.choices,
            selectionlist=template.selectionlist,
            model_type='part'
        ))
    
    if len(templates) > 0:
        ParameterTemplate.objects.bulk_create(templates)
        print(f"\nMigrated {len(templates)} PartParameterTemplate instances.")

    assert ParameterTemplate.objects.filter(model_type='part').count() == len(templates)

    # Next, copy PartParameter instances to Parameter instances
    parameters = []

    for parameter in PartParameter.objects.all():
        # Find the corresponding ParameterTemplate
        template = ParameterTemplate.objects.get(name=parameter.template.name, model_type='part')

        parameters.append(Parameter(
            template=template,
            model_type='part',
            model_id=parameter.part.id,
            data=parameter.data,
            data_numeric=parameter.data_numeric,
            note=parameter.note,
            updated=parameter.updated,
            updated_by=parameter.updated_by
        ))

    if len(parameters) > 0:
        Parameter.objects.bulk_create(parameters)
        print(f"\nMigrated {len(parameters)} PartParameter instances.")

    assert Parameter.objects.filter(model_type='part').count() == len(parameters)


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0132_partparametertemplate_selectionlist"),
        ("common", "0040_parametertemplate_parameter"),
    ]

    operations = [
        migrations.RunPython(
            copy_part_parameters,
            reverse_code=migrations.RunPython.noop
        ),
        # TODO: Data migration for existing ManufacturerPartParameter objects
        # TODO: Data migration for existing CategoryParameter objects
    ]
