# Generated by Django 4.2.20 on 2025-05-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_emailmessage_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='priority',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Very High'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Very Low')], verbose_name='Prioriy'),
        ),
    ]
