# Generated by Django 4.2.25 on 2025-10-28 11:12

from django.db import migrations


def copy_templates(old_model, new_model):
    """Copy from one model type to another."""
    
    templates = []

    # Clear out all existing instances
    new_model.objects.all().delete()

    assert new_model.objects.count() == 0

    for template in old_model.objects.all():
        templates.append(new_model(
            name=template.name,
            description=template.description,
            units=template.units,
            checkbox=template.checkbox,
            choices=template.choices,
            selectionlist=template.selectionlist,
        ))


    if len(templates) > 0:
        new_model.objects.bulk_create(templates)
        print(f"Migrated {len(templates)} ParameterTemplate instances.")

    assert new_model.objects.count() == len(templates)


def forward_copy_templates(apps, schema_editor):
    """Forward migration: copy from PartParameterTemplate to ParameterTemplate."""
    PartParameterTemplate = apps.get_model("part", "PartParameterTemplate")
    ParameterTemplate = apps.get_model("common", "ParameterTemplate")

    copy_templates(PartParameterTemplate, ParameterTemplate)


def reverse_copy_templates(apps, schema_editor):
    """Reverse migration: copy from ParameterTemplate to PartParameterTemplate."""
    ParameterTemplate = apps.get_model("common", "ParameterTemplate")
    PartParameterTemplate = apps.get_model("part", "PartParameterTemplate")

    copy_templates(ParameterTemplate, PartParameterTemplate)


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0132_partparametertemplate_selectionlist"),
        ("common", "0040_parametertemplate"),
    ]

    operations = [
        migrations.RunPython(
            forward_copy_templates,
            reverse_code=reverse_copy_templates
        )
    ]
