# Generated by Django 4.2.20 on 2025-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_rename_recipient_emailmessage_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="delivery_options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
