# Generated by Django 5.2.14 on 2026-05-18 14:16

import InvenTree.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_auto_20251203_1244"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Timestamp of last update",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                ("model_id", models.PositiveIntegerField()),
                (
                    "title",
                    models.CharField(
                        help_text="Note title", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description field",
                        max_length=250,
                        verbose_name="Description",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Note content", verbose_name="Content"
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Update By",
                    ),
                ),
                (
                    "primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary note for the associated model?",
                        verbose_name="Primary",
                    ),
                )
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
    ]
