# Generated by Django 4.2.22 on 2025-07-17 15:42
'''
Migration to copy the image file from the Company model into the UploadedImage model.
'''

import os
from django.db import migrations
from django.core.files.base import ContentFile

def forwards(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    UploadedImage = apps.get_model('common', 'UploadedImage')

    for company in Company.objects.all():
        if not company.image:
            continue

        try:
            company.image.open('rb')
        except Exception:
            # If file is missing or corrupted, skip this Company
            continue

        # Read binary data and close the file
        data = company.image.read()
        company.image.close()

        # Extract the base filename to avoid path issues
        filename = os.path.basename(company.image.name)
        new_img = UploadedImage(
            model_type='company',    
            model_id=company.pk,
            primary=True,
        )
        new_img.image.save(filename, ContentFile(data), save=True)


def backwards(apps, schema_editor):
    # On rollback, remove all UploadedImage entries created for Companies
    UploadedImage = apps.get_model('common', 'UploadedImage')
    UploadedImage.objects.filter(model_type='company').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_migrate_part_images_to_uploadedimage'),
    ]
    
    operations = [
        migrations.RunPython(forwards, backwards),
    ]