# Generated by Django 5.2.14 on 2026-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_auto_20251203_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="is_image",
            field=models.BooleanField(
                default=False,
                help_text="Is this attachment an image?",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for this attachment",
                null=True,
                upload_to="",
                verbose_name="Thumbnail",
            ),
        ),
    ]
