# Generated by Django 5.2.14 on 2026-05-18 12:06

import io
import os

from PIL import Image
from tqdm import tqdm

from time import sleep

from django.db import migrations
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage


def update_image_attachments(apps, schema_editor):
    """Update existing attachments to ensure that image attachments have thumbnails.
    
    For each existing attachment, check if it is an image.
    If it is, generate a thumbnail for it.

    Note: This function mirrors the logic used in the Attachment model's
    check_is_image method, at the time of writing this migration (2026-05-18).

    """
    Attachment = apps.get_model('common', 'Attachment')

    # Find all Attachment instances which (potentially) have a file attached
    attachments = Attachment.objects.exclude(attachment__isnull=True).exclude(attachment='')

    if attachments.count() == 0:
        return

    progress = tqdm(total=attachments.count(), desc='Migration common.0043: Updating attachments')

    for attachment in attachments:
        progress.update(1)
        
        if not attachment.attachment:
            continue
        
        if not attachment.attachment.name or not default_storage.exists(attachment.attachment.name):
            continue

        img_data = default_storage.open(attachment.attachment.name).read()

        try:
            with Image.open(io.BytesIO(img_data)) as img:
                img.verify()  # Verify that this is an image


            # Re-open after verify(), as Pillow invalidates the image object
            with Image.open(io.BytesIO(img_data)) as img:
                img.thumbnail((128, 128))
                thumbnail = io.BytesIO()
                img.save(thumbnail, format='PNG')
                thumbnail.seek(0)

            attachment.thumbnail.save(
                f"thumb_{os.path.basename(attachment.attachment.name)}",
                ContentFile(thumbnail.read())
            )

        except Exception:
            # Not an image, skip this attachment
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0042_attachment_is_image_attachment_thumbnail"),
    ]

    operations = [
        migrations.RunPython(update_image_attachments, reverse_code=migrations.RunPython.noop),
    ]
