# Generated by Django 4.2.22 on 2025-08-05 21:31

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_alter_inventreeimage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventreeimage',
            name='image',
            field=common.models.CustomStdImage(blank=True, force_min_size=False, null=True, upload_to='images', variations={'preview': (256, 256), 'thumbnail': (128, 128)}, verbose_name='Image'),
        ),
    ]
