# Generated by Django 5.2.10 on 2026-02-07 08:37


from django.db import migrations

class Migration(migrations.Migration):
    """Migration to rename 'content_type' field to 'model_type' in InvenTreeImage model."""


    dependencies = [
        ('common', '0044_migrate_company_images'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Rename the 'content_type' field to 'model_type'
        migrations.RenameField(
            model_name='inventreeimage',
            old_name='content_type',
            new_name='model_type',
        ),
    ]

