# Generated by Django 5.2.15 on 2026-06-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0044_notificationmessage_charfield_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcode",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Is this project code active?",
                verbose_name="Active",
            ),
        ),
    ]
