# Generated by Django 5.2.15 on 2026-07-14 00:05

from django.db import migrations, models
from common.models import ParameterTemplate

class Migration(migrations.Migration):

    dependencies = [
        ("common", "0046_alter_emailmessage_global_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametertemplate",
            name="unique",
            field=models.PositiveIntegerField(
                choices=ParameterTemplate.UniqueOptions.choices,
                default=0,
                help_text="Enforce uniqueness of linked parameter values against this template",
                verbose_name="Uniqueness",
            ),
        ),
    ]
