"""Add link field to notification messages."""

# Generated by Django 5.2.15 on 2026-07-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the optional notification link field."""

    dependencies = [('common', '0047_parametertemplate_unique')]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='link',
            field=models.URLField(
                blank=True,
                help_text='Optional explicit URL associated with this notification',
                max_length=500,
                null=True,
            ),
        )
    ]
