# Generated by Django 5.2.15 on 2026-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('common', '0052_remove_notesimage_model_id_and_more')]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_type',
            field=models.CharField(
                choices=[
                    ('text/html', 'HTML'),
                    ('application/json', 'JSON'),
                    ('text/plain', 'Plain text'),
                ],
                default='text/html',
                help_text='Format of the note content; fixed when the note is created',
                max_length=32,
                verbose_name='Content Type',
            ),
        )
    ]
