# Generated by Django 5.2.17 on 2026-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('common', '0052_remove_notesimage_model_id_and_more')]

    operations = [
        migrations.AddField(
            model_name='dataoutput',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        )
    ]
