# Generated by Django 5.2.17 on 2026-09-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_referencesource_reference'),
        ('common', '0052_remove_notesimage_model_id_and_more'),
    ]

    operations = [
    ]
