# Generated by Django 3.0.7 on 2020-08-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemlabel',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Label template is enabled', verbose_name='Enabled'),
        ),
    ]
