# Generated by Django 3.0.7 on 2021-01-08 12:06

import InvenTree.helpers
import django.core.validators
from django.db import migrations, models
import label.models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_stockitemlabel_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label name', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Label description', max_length=250, null=True)),
                ('label', models.FileField(help_text='Label template file', upload_to=label.models.rename_label, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])])),
                ('filters', models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs', max_length=250, validators=[InvenTree.helpers.validateFilterString])),
                ('enabled', models.BooleanField(default=True, help_text='Label template is enabled', verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
