# Generated by Django 3.0.7 on 2021-01-11 12:02

import InvenTree.helpers
import django.core.validators
from django.db import migrations, models
import label.models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_stocklocationlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemlabel',
            name='description',
            field=models.CharField(blank=True, help_text='Label description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stockitemlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs', max_length=250, validators=[InvenTree.helpers.validateFilterString], verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='stockitemlabel',
            name='label',
            field=models.FileField(help_text='Label template file', unique=True, upload_to=label.models.rename_label, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])], verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='stockitemlabel',
            name='name',
            field=models.CharField(help_text='Label name', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stocklocationlabel',
            name='description',
            field=models.CharField(blank=True, help_text='Label description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stocklocationlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs', max_length=250, validators=[InvenTree.helpers.validateFilterString], verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='stocklocationlabel',
            name='label',
            field=models.FileField(help_text='Label template file', unique=True, upload_to=label.models.rename_label, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])], verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='stocklocationlabel',
            name='name',
            field=models.CharField(help_text='Label name', max_length=100, verbose_name='Name'),
        ),
    ]
