# Generated by Django 3.0.7 on 2021-01-13 12:02

from django.db import migrations, models
import label.models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_auto_20210111_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs', max_length=250, validators=[label.models.validate_stock_item_filters], verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='stocklocationlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs', max_length=250, validators=[label.models.validate_stock_location_filters], verbose_name='Filters'),
        ),
    ]
