# Generated by Django 3.2 on 2021-05-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_auto_20210222_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemlabel',
            name='filename_pattern',
            field=models.CharField(default='label.pdf', help_text='Pattern for generating label filenames', max_length=100, verbose_name='Filename Pattern'),
        ),
        migrations.AddField(
            model_name='stocklocationlabel',
            name='filename_pattern',
            field=models.CharField(default='label.pdf', help_text='Pattern for generating label filenames', max_length=100, verbose_name='Filename Pattern'),
        ),
    ]
