# Generated by Django 3.2.19 on 2023-06-23 21:58

from django.db import migrations, models
import label.models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0010_buildlinelabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs)', max_length=250, validators=[label.models.validate_part_filters], verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='stockitemlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs)', max_length=250, validators=[label.models.validate_stock_item_filters], verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='stocklocationlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs)', max_length=250, validators=[label.models.validate_stock_location_filters], verbose_name='Filters'),
        ),
    ]
