# Generated by Django 4.2.23 on 2025-07-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_auto_20201004_0158"),
        ("users", "0003_auto_20201005_2227"),
        ("users", "0004_auto_20210113_1909"),
    ]

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("part_category", "Part Categories"),
                            ("part", "Parts"),
                            ("stock_location", "Stock Locations"),
                            ("stock", "Stock Items"),
                            ("build", "Build Orders"),
                            ("purchase_order", "Purchase Orders"),
                            ("sales_order", "Sales Orders"),
                        ],
                        help_text="Permission set",
                        max_length=50,
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=True,
                        help_text="Permission to view items",
                        verbose_name="View",
                    ),
                ),
                (
                    "can_add",
                    models.BooleanField(
                        default=False,
                        help_text="Permission to add items",
                        verbose_name="Add",
                    ),
                ),
                (
                    "can_change",
                    models.BooleanField(
                        default=False,
                        help_text="Permissions to edit items",
                        verbose_name="Change",
                    ),
                ),
                (
                    "can_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Permission to delete items",
                        verbose_name="Delete",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_sets",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "group")},
            },
        ),
    ]
