# Generated by Django 3.0.7 on 2020-10-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201004_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='can_add',
            field=models.BooleanField(default=False, help_text='Permission to add items', verbose_name='Add'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='can_change',
            field=models.BooleanField(default=False, help_text='Permissions to edit items', verbose_name='Change'),
        ),
    ]
