# Generated by Django 4.2.23 on 2025-07-13 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models
import users.ruleset


class Migration(migrations.Migration):

    replaces = [
        ("users", "0006_alter_ruleset_name"),
        ("users", "0007_alter_ruleset_name"),
        ("users", "0008_apitoken"),
        ("users", "0009_auto_20231020_2356"),
        ("users", "0010_alter_apitoken_key"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_owner_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleset",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("part_category", "Part Categories"),
                    ("part", "Parts"),
                    ("stocktake", "Stocktake"),
                    ("stock_location", "Stock Locations"),
                    ("stock", "Stock Items"),
                    ("build", "Build Orders"),
                    ("purchase_order", "Purchase Orders"),
                    ("sales_order", "Sales Orders"),
                ],
                help_text="Permission set",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="name",
            field=models.CharField(
                choices=[
                    (users.ruleset.RuleSetEnum["ADMIN"], "Admin"),
                    (users.ruleset.RuleSetEnum["PART_CATEGORY"], "Part Categories"),
                    (users.ruleset.RuleSetEnum["PART"], "Parts"),
                    (users.ruleset.RuleSetEnum["STOCKTAKE"], "Stocktake"),
                    (users.ruleset.RuleSetEnum["STOCK_LOCATION"], "Stock Locations"),
                    (users.ruleset.RuleSetEnum["STOCK"], "Stock Items"),
                    (users.ruleset.RuleSetEnum["BUILD"], "Build Orders"),
                    (users.ruleset.RuleSetEnum["PURCHASE_ORDER"], "Purchase Orders"),
                    (users.ruleset.RuleSetEnum["SALES_ORDER"], "Sales Orders"),
                    (users.ruleset.RuleSetEnum["RETURN_ORDER"], "Return Orders"),
                ],
                help_text="Permission set",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=users.models.default_token,
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(50)],
                        verbose_name="Key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Custom token name",
                        max_length=100,
                        verbose_name="Token Name",
                    ),
                ),
                (
                    "expiry",
                    models.DateField(
                        default=users.models.default_token_expiry,
                        help_text="Token expiry date",
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Token has been revoked",
                        verbose_name="Revoked",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "last_seen",
                    models.DateField(
                        blank=True,
                        help_text="Last time the token was used",
                        null=True,
                        verbose_name="Last Seen",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "abstract": False,
                "unique_together": set(),
            },
        ),
    ]
