# Generated by Django 3.2.23 on 2024-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_alter_apitoken_key'),
        ('otp_static', '0002_throttling'),
        ('otp_totp', '0002_auto_20190420_0723'),
        ('mfa', '0002_authenticator_timestamps'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=migrations.RunPython.noop
        )
    ]
