# Generated by Django 4.2.19 on 2025-02-18 23:49

import InvenTree.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def backfill_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0013_migrate_mfa_20240408_1659"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("theme", models.JSONField(blank=True, null=True)),
                ("widgets", models.JSONField(blank=True, null=True)),
                (
                    "displayname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=2000, null=True)),
                ("location", models.CharField(blank=True, max_length=2000, null=True)),
                ("active", models.BooleanField(default=True)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bot", "Bot"),
                            ("internal", "Internal"),
                            ("external", "External"),
                            ("guest", "Guest"),
                        ],
                        default="internal",
                        max_length=10,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_users",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(InvenTree.models.PluginValidationMixin, models.Model),
        ),
        migrations.RunPython(backfill_user_profiles),
    ]
