# Generated by Django 4.2.19 on 2025-02-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0013_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="birth_date",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="displayname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organisation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_users",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="type",
            field=models.CharField(
                choices=[
                    ("bot", "Bot"),
                    ("internal", "Internal"),
                    ("external", "External"),
                    ("guest", "Guest"),
                ],
                default="internal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="widgets",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
