# Generated by Django 5.2.17 on 2026-09-11 06:24

import users.ruleset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_legacy_user_sessions_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleset",
            name="name",
            field=models.CharField(
                choices=[
                    (users.ruleset.RuleSetEnum["ADMIN"], "Admin"),
                    (users.ruleset.RuleSetEnum["PART_CATEGORY"], "Part Categories"),
                    (users.ruleset.RuleSetEnum["PART"], "Parts"),
                    (users.ruleset.RuleSetEnum["BOM"], "Bills of Material"),
                    (users.ruleset.RuleSetEnum["STOCK_LOCATION"], "Stock Locations"),
                    (users.ruleset.RuleSetEnum["STOCK"], "Stock Items"),
                    (users.ruleset.RuleSetEnum["BUILD"], "Build Orders"),
                    (users.ruleset.RuleSetEnum["PURCHASE_ORDER"], "Purchase Orders"),
                    (users.ruleset.RuleSetEnum["SALES_ORDER"], "Sales Orders"),
                    (users.ruleset.RuleSetEnum["RETURN_ORDER"], "Return Orders"),
                    (users.ruleset.RuleSetEnum["TRANSFER_ORDER"], "Transfer Orders"),
                    (users.ruleset.RuleSetEnum["REPAIR_ORDER"], "Repair Orders"),
                ],
                help_text="Permission set",
                max_length=50,
            ),
        ),
    ]
