# Generated by Django 5.2.17 on 2026-09-15 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_tokens_as_v1(apps, schema_editor):
    """Mark tokens created before v2 token support as legacy v1 tokens."""
    ApiToken = apps.get_model('users', 'ApiToken')
    ApiToken.objects.all().update(token_version=1)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_legacy_user_sessions_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='hmac_digest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued the token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Issued By'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='pepper_id',
            field=models.CharField(blank=True, help_text='Identifier for the pepper used in token hashing', max_length=100, null=True, verbose_name='Pepper ID'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='revocation_reason',
            field=models.TextField(blank=True, help_text='As entered by the user or action during revocation', null=True, verbose_name='Revocation Reason'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='User who revoked the token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Revoked By'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='token_version',
            field=models.PositiveSmallIntegerField(default=2, help_text='Version of the API token', verbose_name='Token Version'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Key'),
        ),
        migrations.RunPython(mark_existing_tokens_as_v1, migrations.RunPython.noop),
    ]
