# Generated by Django 5.2.17 on 2026-09-14 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_legacy_user_sessions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='hmac_digest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Key'),
        ),
    ]
