# Generated by Django 5.2.17 on 2026-10-07 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_tippresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tippresult',
            unique_together={('user', 'tipp_id')},
        ),
    ]
