# Generated by Django 3.0.7 on 2020-08-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
    ]
