# Generated by Django 3.0.7 on 2021-02-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210204_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='revision',
            field=models.PositiveIntegerField(default=1, help_text='Report revision number (auto-increments)', verbose_name='Revision'),
        ),
    ]
