# Generated by Django 3.0.7 on 2021-02-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_testreport_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Report revision number (auto-increments)', verbose_name='Revision'),
        ),
    ]
