# Generated by Django 4.2.11 on 2024-04-21 04:55

import os

from django.db import migrations
from django.core.files.base import ContentFile


def report_model_map():
    """Return a map of model_type: report_type keys."""

    return {
        'stockitem': 'testreport',
        'build': 'buildreport',
        'part': 'billofmaterialsreport',
        'purchaseorder': 'purchaseorderreport',
        'salesorder': 'salesorderreport',
        'returnorder': 'returnorderreport'
    }


def forward(apps, schema_editor):
    """Run forwards migration. 
    
    - Create a new ReportTemplate instance for each existing report
    """

    # New 'generic' report template model
    ReportTemplate = apps.get_model('report', 'reporttemplate')

    count = 0

    for key, report_model in report_model_map().items():

        model = apps.get_model('report', report_model)

        for template in model.objects.all():
            # Construct a new ReportTemplate instance

            filename = os.path.basename(template.template.path)
            filedata = template.template.open('r').read()

            ReportTemplate.objects.create(
                name=template.name,
                template=ContentFile(filedata, filename),
                model_type=key,
                description=template.description,
                revision=template.revision,
                page_size=template.page_size,
                landscape=template.landscape,
                filters=template.filters,
                filename_pattern=template.filename_pattern,
                enabled=template.enabled
            )

            count += 1

    if count > 0:
        print(f"Migrated {count} report templates to new ReportTemplate model.")


def reverse(apps, schema_editor):
    """Run reverse migration.

    - Delete any ReportTemplate instances in the database
    """
    ReportTemplate = apps.get_model('report', 'reporttemplate')

    for item in ReportTemplate.objects.all():
        item.template.delete()
        item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_reporttemplate'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=reverse)
    ]
