# Generated by Django 4.2.11 on 2024-04-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_auto_20240421_0455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillOfMaterialsReport',
        ),
        migrations.DeleteModel(
            name='BuildReport',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderReport',
        ),
        migrations.DeleteModel(
            name='ReturnOrderReport',
        ),
        migrations.DeleteModel(
            name='SalesOrderReport',
        ),
        migrations.DeleteModel(
            name='StockLocationReport',
        ),
        migrations.DeleteModel(
            name='TestReport',
        ),
    ]
