# Generated by Django 4.2.23 on 2025-07-13 12:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import report.models
import report.validators


class Migration(migrations.Migration):

    replaces = [
        ("report", "0027_alter_labeltemplate_model_type_and_more"),
        ("report", "0028_labeltemplate_attach_to_model_and_more"),
        ("report", "0029_remove_reportoutput_template_and_more"),
        ("report", "0030_alter_labeltemplate_model_type_and_more"),
        ("report", "0031_reporttemplate_merge"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("report", "0026_auto_20240422_1301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labeltemplate",
            name="model_type",
            field=models.CharField(
                help_text="Target model type for template",
                max_length=100,
                validators=[report.validators.validate_report_model_type],
            ),
        ),
        migrations.AlterField(
            model_name="labeltemplate",
            name="template",
            field=models.FileField(
                help_text="Template file",
                upload_to=report.models.rename_template,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
                verbose_name="Template",
            ),
        ),
        migrations.AlterField(
            model_name="reportasset",
            name="asset",
            field=models.FileField(
                help_text="Report asset file",
                upload_to=report.models.rename_template,
                verbose_name="Asset",
            ),
        ),
        migrations.AlterField(
            model_name="reportsnippet",
            name="snippet",
            field=models.FileField(
                help_text="Report snippet file",
                upload_to=report.models.rename_template,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
                verbose_name="Snippet",
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="template",
            field=models.FileField(
                help_text="Template file",
                upload_to=report.models.rename_template,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
                verbose_name="Template",
            ),
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="attach_to_model",
            field=models.BooleanField(
                default=False,
                help_text="Save report output as an attachment against linked model instance when printing",
                verbose_name="Attach to Model on Print",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="attach_to_model",
            field=models.BooleanField(
                default=False,
                help_text="Save report output as an attachment against linked model instance when printing",
                verbose_name="Attach to Model on Print",
            ),
        ),
        migrations.AlterField(
            model_name="labeltemplate",
            name="model_type",
            field=models.CharField(
                help_text="Target model type for template",
                max_length=100,
                validators=[report.validators.validate_report_model_type],
                verbose_name="Model Type",
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="model_type",
            field=models.CharField(
                help_text="Target model type for template",
                max_length=100,
                validators=[report.validators.validate_report_model_type],
                verbose_name="Model Type",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="merge",
            field=models.BooleanField(
                default=False,
                help_text="Render a single report against selected items",
                verbose_name="Merge",
            ),
        ),
    ]
