# Generated by Django 4.2.11 on 2024-04-29 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0026_auto_20240422_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, help_text='Report generation is complete', verbose_name='Complete')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Report generation progress', verbose_name='Progress')),
                ('output', models.FileField(blank=True, help_text='Generated output file', null=True, upload_to='report/output', verbose_name='Output File')),
                ('template_id', models.PositiveIntegerField(blank=True, null=True)),
                ('template_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
