# Generated by Django 4.2.20 on 2025-04-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0030_alter_labeltemplate_model_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="merge",
            field=models.BooleanField(
                default=False,
                help_text="Render a single report against selected items",
                verbose_name="Merge",
            ),
        ),
    ]
