# Generated by Django 4.2.20 on 2025-04-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0030_alter_labeltemplate_model_type_and_more"),
        ("report", "0030_reporttemplate_merge"),
    ]

    operations = []
