"""Builtin plugin for providing pricing functionality."""

from django.utils.translation import gettext_lazy as _

import structlog

from common.pricing import PriceRangeTuple
from plugin import InvenTreePlugin
from plugin.mixins import PricingMixin, SettingsMixin

logger = structlog.get_logger('inventree')


class InvenTreePricingPlugin(PricingMixin, SettingsMixin, InvenTreePlugin):
    """Default InvenTree plugin for pricing functionality."""

    NAME = 'InvenTreePricingPlugin'
    SLUG = 'inventree-pricing'
    AUTHOR = _('InvenTree contributors')
    TITLE = _('InvenTree Pricing Plugin')
    DESCRIPTION = _('Provides default pricing integration functionality for InvenTree')
    VERSION = '1.0.0'

    def calculate_part_overall_price_range(
        self, part, *args, **kwargs
    ) -> PriceRangeTuple:
        """Calculate the overall price for a given part.

        Arguments:
            part: The part instance for which to calculate the price.
            *args, **kwargs: Additional arguments for price calculation.

        Returns:
            A tuple representing the min, max price range for the part

        The default implementation calculates the price range based on
        the overall price range generated by the part's pricing data.
        """

    def calculate_part_bom_price_range(self, part, *args, **kwargs) -> PriceRangeTuple:
        """Calculate the assembly price range for a given part.

        Arguments:
            part: The part instance for which to calculate the BOM price.
            *args, **kwargs: Additional arguments for BOM price calculation.

        Returns:
            A tuple representing the min, max BOM price range for the part

        The "BOM price range" is the cost of manufacturing the assembly
        from its constituent parts, based on their pricing data.
        """

    def calculate_part_purchase_price_range(
        self, part, *args, **kwargs
    ) -> PriceRangeTuple:
        """Calculate the purchase price range for a given part.

        Arguments:
            part: The part instance for which to calculate the purchase price.
            *args, **kwargs: Additional arguments for purchase price calculation.

        Returns:
            A tuple representing the min, max purchase price range for the part

        The "purchase price range" is the cost to purchase the part from suppliers,
        """

    def calculate_part_supplier_price_range(
        self, part, *args, **kwargs
    ) -> PriceRangeTuple:
        """Calculate the supplier price range for a given part.

        Arguments:
            part: The part instance for which to calculate the supplier price.
            *args, **kwargs: Additional arguments for supplier price calculation.

        Returns:
            A tuple representing the min, max supplier price range for the part
        """

    def calculate_part_internal_price_range(
        self, part, *args, **kwargs
    ) -> PriceRangeTuple:
        """Calculate the internal price range for a given part.

        Arguments:
            part: The part instance for which to calculate the internal price.
            *args, **kwargs: Additional arguments for internal price calculation.

        Returns:
            A tuple representing the min, max internal price range for the part
        """

    def calculate_part_variant_price_range(
        self, part, *args, **kwargs
    ) -> PriceRangeTuple:
        """Calculate the variant price range for a given part.

        Arguments:
            part: The part instance for which to calculate the variant price.
            *args, **kwargs: Additional arguments for variant price calculation.

        Returns:
            A tuple representing the min, max variant price range for the part

        The "variant price range" is the price range for all variants of a template part
        """

    def calculate_part_sale_price_range(self, part, *args, **kwargs) -> PriceRangeTuple:
        """Calculate the sale price range for a given part.

        Arguments:
            part: The part instance for which to calculate the sale price.
            *args, **kwargs: Additional arguments for sale price calculation.

        Returns:
            A tuple representing the min, max sale price range for the part
        """
